"""
Complete HSK 5 vocabulary - ~1300 words
Based on official HSK 5.0 word list
"""
import sys
import io
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

from app.database import SessionLocal
from app.models import HanziWord

hsk5_words = [
    # ── Nouns: People & Relationships ──
    {"simplified": "人才", "traditional": "人才", "pinyin": "rén cái", "english": "talent; talented person", "category": "noun"},
    {"simplified": "人物", "traditional": "人物", "pinyin": "rén wù", "english": "figure; character; personage", "category": "noun"},
    {"simplified": "人员", "traditional": "人員", "pinyin": "rén yuán", "english": "personnel; staff", "category": "noun"},
    {"simplified": "人类", "traditional": "人類", "pinyin": "rén lèi", "english": "humanity; mankind", "category": "noun"},
    {"simplified": "主人", "traditional": "主人", "pinyin": "zhǔ rén", "english": "host; master; owner", "category": "noun"},
    {"simplified": "对手", "traditional": "對手", "pinyin": "duì shǒu", "english": "opponent; rival", "category": "noun"},
    {"simplified": "对象", "traditional": "對象", "pinyin": "duì xiàng", "english": "target; object; partner", "category": "noun"},
    {"simplified": "伙伴", "traditional": "伙伴", "pinyin": "huǒ bàn", "english": "partner; companion", "category": "noun"},
    {"simplified": "群众", "traditional": "群眾", "pinyin": "qún zhòng", "english": "the masses; the public", "category": "noun"},
    {"simplified": "青少年", "traditional": "青少年", "pinyin": "qīng shào nián", "english": "teenager; youth", "category": "noun"},
    {"simplified": "老百姓", "traditional": "老百姓", "pinyin": "lǎo bǎi xìng", "english": "common people; civilians", "category": "noun"},
    {"simplified": "志愿者", "traditional": "志願者", "pinyin": "zhì yuàn zhě", "english": "volunteer", "category": "noun"},
    {"simplified": "家庭", "traditional": "家庭", "pinyin": "jiā tíng", "english": "family; household", "category": "noun"},
    {"simplified": "家乡", "traditional": "家鄉", "pinyin": "jiā xiāng", "english": "hometown", "category": "noun"},
    {"simplified": "祖国", "traditional": "祖國", "pinyin": "zǔ guó", "english": "motherland; homeland", "category": "noun"},
    # ── Nouns: Society & Government ──
    {"simplified": "社会", "traditional": "社會", "pinyin": "shè huì", "english": "society", "category": "noun"},
    {"simplified": "国家", "traditional": "國家", "pinyin": "guó jiā", "english": "country; nation", "category": "noun"},
    {"simplified": "政府", "traditional": "政府", "pinyin": "zhèng fǔ", "english": "government", "category": "noun"},
    {"simplified": "民族", "traditional": "民族", "pinyin": "mín zú", "english": "ethnic group; nation", "category": "noun"},
    {"simplified": "人民", "traditional": "人民", "pinyin": "rén mín", "english": "the people", "category": "noun"},
    {"simplified": "公民", "traditional": "公民", "pinyin": "gōng mín", "english": "citizen", "category": "noun"},
    {"simplified": "制度", "traditional": "制度", "pinyin": "zhì dù", "english": "system; institution", "category": "noun"},
    {"simplified": "政策", "traditional": "政策", "pinyin": "zhèng cè", "english": "policy", "category": "noun"},
    {"simplified": "法律", "traditional": "法律", "pinyin": "fǎ lǜ", "english": "law", "category": "noun"},
    {"simplified": "规定", "traditional": "規定", "pinyin": "guī dìng", "english": "regulation; rule", "category": "noun"},
    {"simplified": "权利", "traditional": "權利", "pinyin": "quán lì", "english": "right; privilege", "category": "noun"},
    {"simplified": "义务", "traditional": "義務", "pinyin": "yì wù", "english": "duty; obligation", "category": "noun"},
    {"simplified": "自由", "traditional": "自由", "pinyin": "zì yóu", "english": "freedom; liberty", "category": "noun"},
    {"simplified": "和平", "traditional": "和平", "pinyin": "hé píng", "english": "peace", "category": "noun"},
    {"simplified": "战争", "traditional": "戰爭", "pinyin": "zhàn zhēng", "english": "war", "category": "noun"},
    {"simplified": "矛盾", "traditional": "矛盾", "pinyin": "máo dùn", "english": "contradiction; conflict", "category": "noun"},
    {"simplified": "合作", "traditional": "合作", "pinyin": "hé zuò", "english": "cooperation; to cooperate", "category": "noun"},
    {"simplified": "竞争", "traditional": "競爭", "pinyin": "jìng zhēng", "english": "competition", "category": "noun"},
    # ── Nouns: Economy & Business ──
    {"simplified": "经济", "traditional": "經濟", "pinyin": "jīng jì", "english": "economy; economics", "category": "noun"},
    {"simplified": "市场", "traditional": "市場", "pinyin": "shì chǎng", "english": "market", "category": "noun"},
    {"simplified": "企业", "traditional": "企業", "pinyin": "qǐ yè", "english": "enterprise; company", "category": "noun"},
    {"simplified": "品牌", "traditional": "品牌", "pinyin": "pǐn pái", "english": "brand", "category": "noun"},
    {"simplified": "产品", "traditional": "產品", "pinyin": "chǎn pǐn", "english": "product", "category": "noun"},
    {"simplified": "商品", "traditional": "商品", "pinyin": "shāng pǐn", "english": "goods; commodity", "category": "noun"},
    {"simplified": "贸易", "traditional": "貿易", "pinyin": "mào yì", "english": "trade; commerce", "category": "noun"},
    {"simplified": "投资", "traditional": "投資", "pinyin": "tóu zī", "english": "investment", "category": "noun"},
    {"simplified": "利润", "traditional": "利潤", "pinyin": "lì rùn", "english": "profit", "category": "noun"},
    {"simplified": "成本", "traditional": "成本", "pinyin": "chéng běn", "english": "cost", "category": "noun"},
    {"simplified": "费用", "traditional": "費用", "pinyin": "fèi yòng", "english": "expense; cost", "category": "noun"},
    {"simplified": "收入", "traditional": "收入", "pinyin": "shōu rù", "english": "income; revenue", "category": "noun"},
    {"simplified": "工资", "traditional": "工資", "pinyin": "gōng zī", "english": "salary; wages", "category": "noun"},
    {"simplified": "价值", "traditional": "價值", "pinyin": "jià zhí", "english": "value; worth", "category": "noun"},
    {"simplified": "产业", "traditional": "產業", "pinyin": "chǎn yè", "english": "industry; estate", "category": "noun"},
    {"simplified": "行业", "traditional": "行業", "pinyin": "háng yè", "english": "industry; profession", "category": "noun"},
    {"simplified": "消费", "traditional": "消費", "pinyin": "xiāo fèi", "english": "consumption; to consume", "category": "noun"},
    {"simplified": "生产", "traditional": "生產", "pinyin": "shēng chǎn", "english": "production; to produce", "category": "noun"},
    {"simplified": "供应", "traditional": "供應", "pinyin": "gōng yìng", "english": "supply", "category": "noun"},
    {"simplified": "需求", "traditional": "需求", "pinyin": "xū qiú", "english": "demand; requirement", "category": "noun"},
    # ── Nouns: Science & Technology ──
    {"simplified": "科技", "traditional": "科技", "pinyin": "kē jì", "english": "science and technology", "category": "noun"},
    {"simplified": "技术", "traditional": "技術", "pinyin": "jì shù", "english": "technology; technique", "category": "noun"},
    {"simplified": "研究", "traditional": "研究", "pinyin": "yán jiū", "english": "research; to study", "category": "noun"},
    {"simplified": "实验", "traditional": "實驗", "pinyin": "shí yàn", "english": "experiment", "category": "noun"},
    {"simplified": "数据", "traditional": "數據", "pinyin": "shù jù", "english": "data", "category": "noun"},
    {"simplified": "网络", "traditional": "網絡", "pinyin": "wǎng luò", "english": "network; internet", "category": "noun"},
    {"simplified": "系统", "traditional": "系統", "pinyin": "xì tǒng", "english": "system", "category": "noun"},
    {"simplified": "程序", "traditional": "程序", "pinyin": "chéng xù", "english": "program; procedure", "category": "noun"},
    {"simplified": "软件", "traditional": "軟件", "pinyin": "ruǎn jiàn", "english": "software", "category": "noun"},
    {"simplified": "设备", "traditional": "設備", "pinyin": "shè bèi", "english": "equipment; device", "category": "noun"},
    {"simplified": "材料", "traditional": "材料", "pinyin": "cái liào", "english": "material", "category": "noun"},
    {"simplified": "能源", "traditional": "能源", "pinyin": "néng yuán", "english": "energy source", "category": "noun"},
    {"simplified": "资源", "traditional": "資源", "pinyin": "zī yuán", "english": "resource", "category": "noun"},
    {"simplified": "环境", "traditional": "環境", "pinyin": "huán jìng", "english": "environment", "category": "noun"},
    {"simplified": "污染", "traditional": "污染", "pinyin": "wū rǎn", "english": "pollution; to pollute", "category": "noun"},
    # ── Nouns: Education & Academic ──
    {"simplified": "教育", "traditional": "教育", "pinyin": "jiào yù", "english": "education", "category": "noun"},
    {"simplified": "知识", "traditional": "知識", "pinyin": "zhī shi", "english": "knowledge", "category": "noun"},
    {"simplified": "学术", "traditional": "學術", "pinyin": "xué shù", "english": "academic; scholarship", "category": "noun"},
    {"simplified": "理论", "traditional": "理論", "pinyin": "lǐ lùn", "english": "theory", "category": "noun"},
    {"simplified": "概念", "traditional": "概念", "pinyin": "gài niàn", "english": "concept; idea", "category": "noun"},
    {"simplified": "原则", "traditional": "原則", "pinyin": "yuán zé", "english": "principle", "category": "noun"},
    {"simplified": "标准", "traditional": "標準", "pinyin": "biāo zhǔn", "english": "standard; criterion", "category": "noun"},
    {"simplified": "方案", "traditional": "方案", "pinyin": "fāng àn", "english": "plan; scheme", "category": "noun"},
    {"simplified": "目标", "traditional": "目標", "pinyin": "mù biāo", "english": "goal; target", "category": "noun"},
    {"simplified": "结构", "traditional": "結構", "pinyin": "jié gòu", "english": "structure", "category": "noun"},
    {"simplified": "模式", "traditional": "模式", "pinyin": "mó shì", "english": "pattern; model", "category": "noun"},
    {"simplified": "趋势", "traditional": "趨勢", "pinyin": "qū shì", "english": "trend; tendency", "category": "noun"},
    {"simplified": "现象", "traditional": "現象", "pinyin": "xiàn xiàng", "english": "phenomenon", "category": "noun"},
    {"simplified": "因素", "traditional": "因素", "pinyin": "yīn sù", "english": "factor; element", "category": "noun"},
    {"simplified": "条件", "traditional": "條件", "pinyin": "tiáo jiàn", "english": "condition; term", "category": "noun"},
    {"simplified": "特征", "traditional": "特徵", "pinyin": "tè zhēng", "english": "characteristic; feature", "category": "noun"},
    {"simplified": "功能", "traditional": "功能", "pinyin": "gōng néng", "english": "function; capability", "category": "noun"},
    {"simplified": "效果", "traditional": "效果", "pinyin": "xiào guǒ", "english": "effect; result", "category": "noun"},
    {"simplified": "意义", "traditional": "意義", "pinyin": "yì yì", "english": "meaning; significance", "category": "noun"},
    {"simplified": "地位", "traditional": "地位", "pinyin": "dì wèi", "english": "status; position", "category": "noun"},
    {"simplified": "范围", "traditional": "範圍", "pinyin": "fàn wéi", "english": "scope; range", "category": "noun"},
    {"simplified": "程度", "traditional": "程度", "pinyin": "chéng dù", "english": "degree; extent", "category": "noun"},
    {"simplified": "比例", "traditional": "比例", "pinyin": "bǐ lì", "english": "proportion; ratio", "category": "noun"},
    {"simplified": "数量", "traditional": "數量", "pinyin": "shù liàng", "english": "quantity; amount", "category": "noun"},
    {"simplified": "质量", "traditional": "質量", "pinyin": "zhì liàng", "english": "quality; mass", "category": "noun"},
    {"simplified": "效率", "traditional": "效率", "pinyin": "xiào lǜ", "english": "efficiency", "category": "noun"},
    # ── Nouns: Health ──
    {"simplified": "健康", "traditional": "健康", "pinyin": "jiàn kāng", "english": "health; healthy", "category": "noun"},
    {"simplified": "疾病", "traditional": "疾病", "pinyin": "jí bìng", "english": "disease; illness", "category": "noun"},
    {"simplified": "症状", "traditional": "症狀", "pinyin": "zhèng zhuàng", "english": "symptom", "category": "noun"},
    {"simplified": "治疗", "traditional": "治療", "pinyin": "zhì liáo", "english": "treatment; to treat", "category": "noun"},
    {"simplified": "手术", "traditional": "手術", "pinyin": "shǒu shù", "english": "surgery; operation", "category": "noun"},
    {"simplified": "营养", "traditional": "營養", "pinyin": "yíng yǎng", "english": "nutrition", "category": "noun"},
    {"simplified": "心理", "traditional": "心理", "pinyin": "xīn lǐ", "english": "psychology; mentality", "category": "noun"},
    {"simplified": "情绪", "traditional": "情緒", "pinyin": "qíng xù", "english": "mood; emotion", "category": "noun"},
    {"simplified": "压力", "traditional": "壓力", "pinyin": "yā lì", "english": "pressure; stress", "category": "noun"},
    # ── Nouns: Culture & Misc ──
    {"simplified": "文化", "traditional": "文化", "pinyin": "wén huà", "english": "culture", "category": "noun"},
    {"simplified": "传统", "traditional": "傳統", "pinyin": "chuán tǒng", "english": "tradition; traditional", "category": "noun"},
    {"simplified": "文学", "traditional": "文學", "pinyin": "wén xué", "english": "literature", "category": "noun"},
    {"simplified": "艺术", "traditional": "藝術", "pinyin": "yì shù", "english": "art", "category": "noun"},
    {"simplified": "风格", "traditional": "風格", "pinyin": "fēng gé", "english": "style", "category": "noun"},
    {"simplified": "形象", "traditional": "形象", "pinyin": "xíng xiàng", "english": "image; appearance", "category": "noun"},
    {"simplified": "气氛", "traditional": "氣氛", "pinyin": "qì fēn", "english": "atmosphere; mood", "category": "noun"},
    {"simplified": "背景", "traditional": "背景", "pinyin": "bèi jǐng", "english": "background", "category": "noun"},
    {"simplified": "阶段", "traditional": "階段", "pinyin": "jiē duàn", "english": "phase; stage", "category": "noun"},
    {"simplified": "过程", "traditional": "過程", "pinyin": "guò chéng", "english": "process; course", "category": "noun"},
    {"simplified": "现实", "traditional": "現實", "pinyin": "xiàn shí", "english": "reality; actual", "category": "noun"},
    {"simplified": "事实", "traditional": "事實", "pinyin": "shì shí", "english": "fact", "category": "noun"},
    {"simplified": "道理", "traditional": "道理", "pinyin": "dào lǐ", "english": "reason; principle", "category": "noun"},
    {"simplified": "角度", "traditional": "角度", "pinyin": "jiǎo dù", "english": "angle; perspective", "category": "noun"},
    {"simplified": "命运", "traditional": "命運", "pinyin": "mìng yùn", "english": "fate; destiny", "category": "noun"},
    {"simplified": "幸福", "traditional": "幸福", "pinyin": "xìng fú", "english": "happiness; happy", "category": "noun"},
    {"simplified": "智慧", "traditional": "智慧", "pinyin": "zhì huì", "english": "wisdom; intelligence", "category": "noun"},
    {"simplified": "灵魂", "traditional": "靈魂", "pinyin": "líng hún", "english": "soul; spirit", "category": "noun"},
    {"simplified": "道德", "traditional": "道德", "pinyin": "dào dé", "english": "morality; ethics", "category": "noun"},
    {"simplified": "信念", "traditional": "信念", "pinyin": "xìn niàn", "english": "belief; conviction", "category": "noun"},
    {"simplified": "观念", "traditional": "觀念", "pinyin": "guān niàn", "english": "concept; idea", "category": "noun"},
    {"simplified": "思想", "traditional": "思想", "pinyin": "sī xiǎng", "english": "thought; ideology", "category": "noun"},
    {"simplified": "意识", "traditional": "意識", "pinyin": "yì shí", "english": "consciousness; awareness", "category": "noun"},
    {"simplified": "精神", "traditional": "精神", "pinyin": "jīng shén", "english": "spirit; mind", "category": "noun"},
    {"simplified": "力量", "traditional": "力量", "pinyin": "lì liàng", "english": "power; force; strength", "category": "noun"},
    {"simplified": "能力", "traditional": "能力", "pinyin": "néng lì", "english": "ability; capability", "category": "noun"},
    {"simplified": "素质", "traditional": "素質", "pinyin": "sù zhì", "english": "quality; character", "category": "noun"},
    {"simplified": "优势", "traditional": "優勢", "pinyin": "yōu shì", "english": "advantage; superiority", "category": "noun"},
    {"simplified": "责任", "traditional": "責任", "pinyin": "zé rèn", "english": "responsibility", "category": "noun"},
    {"simplified": "任务", "traditional": "任務", "pinyin": "rèn wù", "english": "task; mission", "category": "noun"},
    {"simplified": "贡献", "traditional": "貢獻", "pinyin": "gòng xiàn", "english": "contribution", "category": "noun"},
    {"simplified": "成就", "traditional": "成就", "pinyin": "chéng jiù", "english": "achievement", "category": "noun"},
    {"simplified": "前途", "traditional": "前途", "pinyin": "qián tú", "english": "future; prospects", "category": "noun"},
    {"simplified": "领域", "traditional": "領域", "pinyin": "lǐng yù", "english": "field; domain; realm", "category": "noun"},
    {"simplified": "项目", "traditional": "項目", "pinyin": "xiàng mù", "english": "project; item", "category": "noun"},
    {"simplified": "工程", "traditional": "工程", "pinyin": "gōng chéng", "english": "engineering; project", "category": "noun"},
    {"simplified": "方式", "traditional": "方式", "pinyin": "fāng shì", "english": "way; method; manner", "category": "noun"},
    {"simplified": "途径", "traditional": "途徑", "pinyin": "tú jìng", "english": "approach; channel", "category": "noun"},
    {"simplified": "措施", "traditional": "措施", "pinyin": "cuò shī", "english": "measure; step", "category": "noun"},
    {"simplified": "策略", "traditional": "策略", "pinyin": "cè lüè", "english": "strategy; tactic", "category": "noun"},
    {"simplified": "基础", "traditional": "基礎", "pinyin": "jī chǔ", "english": "foundation; basis", "category": "noun"},
    {"simplified": "根据", "traditional": "根據", "pinyin": "gēn jù", "english": "basis; according to", "category": "noun"},
    {"simplified": "证据", "traditional": "證據", "pinyin": "zhèng jù", "english": "evidence; proof", "category": "noun"},
    {"simplified": "信息", "traditional": "信息", "pinyin": "xìn xī", "english": "information; message", "category": "noun"},
    {"simplified": "资料", "traditional": "資料", "pinyin": "zī liào", "english": "data; material; information", "category": "noun"},
    {"simplified": "文件", "traditional": "文件", "pinyin": "wén jiàn", "english": "document; file", "category": "noun"},
    {"simplified": "内容", "traditional": "內容", "pinyin": "nèi róng", "english": "content", "category": "noun"},
    {"simplified": "形式", "traditional": "形式", "pinyin": "xíng shì", "english": "form; format", "category": "noun"},
    {"simplified": "规模", "traditional": "規模", "pinyin": "guī mó", "english": "scale; scope", "category": "noun"},
    {"simplified": "情况", "traditional": "情況", "pinyin": "qíng kuàng", "english": "situation; circumstance", "category": "noun"},
    {"simplified": "状况", "traditional": "狀況", "pinyin": "zhuàng kuàng", "english": "condition; state", "category": "noun"},
    {"simplified": "局面", "traditional": "局面", "pinyin": "jú miàn", "english": "situation; aspect", "category": "noun"},
    {"simplified": "危机", "traditional": "危機", "pinyin": "wēi jī", "english": "crisis", "category": "noun"},
    # ── Verbs ──
    {"simplified": "承担", "traditional": "承擔", "pinyin": "chéng dān", "english": "to undertake; to bear", "category": "verb"},
    {"simplified": "承认", "traditional": "承認", "pinyin": "chéng rèn", "english": "to admit; to acknowledge", "category": "verb"},
    {"simplified": "产生", "traditional": "產生", "pinyin": "chǎn shēng", "english": "to produce; to arise", "category": "verb"},
    {"simplified": "促进", "traditional": "促進", "pinyin": "cù jìn", "english": "to promote; to advance", "category": "verb"},
    {"simplified": "创造", "traditional": "創造", "pinyin": "chuàng zào", "english": "to create; to produce", "category": "verb"},
    {"simplified": "采取", "traditional": "採取", "pinyin": "cǎi qǔ", "english": "to adopt; to take", "category": "verb"},
    {"simplified": "处理", "traditional": "處理", "pinyin": "chǔ lǐ", "english": "to handle; to deal with", "category": "verb"},
    {"simplified": "传播", "traditional": "傳播", "pinyin": "chuán bō", "english": "to spread; to broadcast", "category": "verb"},
    {"simplified": "代表", "traditional": "代表", "pinyin": "dài biǎo", "english": "to represent; representative", "category": "verb"},
    {"simplified": "导致", "traditional": "導致", "pinyin": "dǎo zhì", "english": "to lead to; to cause", "category": "verb"},
    {"simplified": "调整", "traditional": "調整", "pinyin": "tiáo zhěng", "english": "to adjust; to regulate", "category": "verb"},
    {"simplified": "发表", "traditional": "發表", "pinyin": "fā biǎo", "english": "to publish; to express", "category": "verb"},
    {"simplified": "发挥", "traditional": "發揮", "pinyin": "fā huī", "english": "to bring into play; to display", "category": "verb"},
    {"simplified": "防止", "traditional": "防止", "pinyin": "fáng zhǐ", "english": "to prevent; to guard against", "category": "verb"},
    {"simplified": "反映", "traditional": "反映", "pinyin": "fǎn yìng", "english": "to reflect; to report", "category": "verb"},
    {"simplified": "分析", "traditional": "分析", "pinyin": "fēn xī", "english": "to analyze; analysis", "category": "verb"},
    {"simplified": "分配", "traditional": "分配", "pinyin": "fēn pèi", "english": "to distribute; to assign", "category": "verb"},
    {"simplified": "改善", "traditional": "改善", "pinyin": "gǎi shàn", "english": "to improve; to ameliorate", "category": "verb"},
    {"simplified": "估计", "traditional": "估計", "pinyin": "gū jì", "english": "to estimate; to reckon", "category": "verb"},
    {"simplified": "归纳", "traditional": "歸納", "pinyin": "guī nà", "english": "to summarize; to induce", "category": "verb"},
    {"simplified": "恢复", "traditional": "恢復", "pinyin": "huī fù", "english": "to recover; to restore", "category": "verb"},
    {"simplified": "获得", "traditional": "獲得", "pinyin": "huò dé", "english": "to obtain; to gain", "category": "verb"},
    {"simplified": "激发", "traditional": "激發", "pinyin": "jī fā", "english": "to stimulate; to inspire", "category": "verb"},
    {"simplified": "记录", "traditional": "記錄", "pinyin": "jì lù", "english": "to record; record", "category": "verb"},
    {"simplified": "建设", "traditional": "建設", "pinyin": "jiàn shè", "english": "to build; to construct", "category": "verb"},
    {"simplified": "建立", "traditional": "建立", "pinyin": "jiàn lì", "english": "to establish; to set up", "category": "verb"},
    {"simplified": "经营", "traditional": "經營", "pinyin": "jīng yíng", "english": "to operate; to manage", "category": "verb"},
    {"simplified": "具备", "traditional": "具備", "pinyin": "jù bèi", "english": "to possess; to have", "category": "verb"},
    {"simplified": "克服", "traditional": "克服", "pinyin": "kè fú", "english": "to overcome; to conquer", "category": "verb"},
    {"simplified": "控制", "traditional": "控制", "pinyin": "kòng zhì", "english": "to control", "category": "verb"},
    {"simplified": "理解", "traditional": "理解", "pinyin": "lǐ jiě", "english": "to understand; to comprehend", "category": "verb"},
    {"simplified": "利用", "traditional": "利用", "pinyin": "lì yòng", "english": "to utilize; to make use of", "category": "verb"},
    {"simplified": "面临", "traditional": "面臨", "pinyin": "miàn lín", "english": "to face; to confront", "category": "verb"},
    {"simplified": "描述", "traditional": "描述", "pinyin": "miáo shù", "english": "to describe; description", "category": "verb"},
    {"simplified": "模仿", "traditional": "模仿", "pinyin": "mó fǎng", "english": "to imitate; to copy", "category": "verb"},
    {"simplified": "配合", "traditional": "配合", "pinyin": "pèi hé", "english": "to cooperate; to coordinate", "category": "verb"},
    {"simplified": "评估", "traditional": "評估", "pinyin": "píng gū", "english": "to evaluate; to assess", "category": "verb"},
    {"simplified": "破坏", "traditional": "破壞", "pinyin": "pò huài", "english": "to destroy; to damage", "category": "verb"},
    {"simplified": "启发", "traditional": "啟發", "pinyin": "qǐ fā", "english": "to inspire; to enlighten", "category": "verb"},
    {"simplified": "强调", "traditional": "強調", "pinyin": "qiáng diào", "english": "to emphasize; to stress", "category": "verb"},
    {"simplified": "确保", "traditional": "確保", "pinyin": "què bǎo", "english": "to ensure; to guarantee", "category": "verb"},
    {"simplified": "确立", "traditional": "確立", "pinyin": "què lì", "english": "to establish firmly", "category": "verb"},
    {"simplified": "忍受", "traditional": "忍受", "pinyin": "rěn shòu", "english": "to endure; to bear", "category": "verb"},
    {"simplified": "融合", "traditional": "融合", "pinyin": "róng hé", "english": "to merge; to integrate", "category": "verb"},
    {"simplified": "实施", "traditional": "實施", "pinyin": "shí shī", "english": "to implement; to carry out", "category": "verb"},
    {"simplified": "实践", "traditional": "實踐", "pinyin": "shí jiàn", "english": "to practice; practice", "category": "verb"},
    {"simplified": "实现", "traditional": "實現", "pinyin": "shí xiàn", "english": "to achieve; to realize", "category": "verb"},
    {"simplified": "收集", "traditional": "收集", "pinyin": "shōu jí", "english": "to collect; to gather", "category": "verb"},
    {"simplified": "属于", "traditional": "屬於", "pinyin": "shǔ yú", "english": "to belong to", "category": "verb"},
    {"simplified": "思考", "traditional": "思考", "pinyin": "sī kǎo", "english": "to think; to ponder", "category": "verb"},
    {"simplified": "探索", "traditional": "探索", "pinyin": "tàn suǒ", "english": "to explore; to probe", "category": "verb"},
    {"simplified": "提倡", "traditional": "提倡", "pinyin": "tí chàng", "english": "to advocate; to promote", "category": "verb"},
    {"simplified": "提出", "traditional": "提出", "pinyin": "tí chū", "english": "to put forward; to propose", "category": "verb"},
    {"simplified": "体现", "traditional": "體現", "pinyin": "tǐ xiàn", "english": "to embody; to reflect", "category": "verb"},
    {"simplified": "推动", "traditional": "推動", "pinyin": "tuī dòng", "english": "to promote; to push forward", "category": "verb"},
    {"simplified": "推荐", "traditional": "推薦", "pinyin": "tuī jiàn", "english": "to recommend", "category": "verb"},
    {"simplified": "维持", "traditional": "維持", "pinyin": "wéi chí", "english": "to maintain; to keep", "category": "verb"},
    {"simplified": "维护", "traditional": "維護", "pinyin": "wéi hù", "english": "to protect; to safeguard", "category": "verb"},
    {"simplified": "吸收", "traditional": "吸收", "pinyin": "xī shōu", "english": "to absorb; to take in", "category": "verb"},
    {"simplified": "限制", "traditional": "限制", "pinyin": "xiàn zhì", "english": "to restrict; to limit", "category": "verb"},
    {"simplified": "消除", "traditional": "消除", "pinyin": "xiāo chú", "english": "to eliminate; to remove", "category": "verb"},
    {"simplified": "协调", "traditional": "協調", "pinyin": "xié tiáo", "english": "to coordinate", "category": "verb"},
    {"simplified": "修改", "traditional": "修改", "pinyin": "xiū gǎi", "english": "to revise; to modify", "category": "verb"},
    {"simplified": "宣传", "traditional": "宣傳", "pinyin": "xuān chuán", "english": "to publicize; propaganda", "category": "verb"},
    {"simplified": "宣布", "traditional": "宣佈", "pinyin": "xuān bù", "english": "to announce; to declare", "category": "verb"},
    {"simplified": "延长", "traditional": "延長", "pinyin": "yán cháng", "english": "to extend; to prolong", "category": "verb"},
    {"simplified": "验证", "traditional": "驗證", "pinyin": "yàn zhèng", "english": "to verify; to confirm", "category": "verb"},
    {"simplified": "运用", "traditional": "運用", "pinyin": "yùn yòng", "english": "to apply; to use", "category": "verb"},
    {"simplified": "掌握", "traditional": "掌握", "pinyin": "zhǎng wò", "english": "to master; to grasp", "category": "verb"},
    {"simplified": "执行", "traditional": "執行", "pinyin": "zhí xíng", "english": "to execute; to carry out", "category": "verb"},
    {"simplified": "指导", "traditional": "指導", "pinyin": "zhǐ dǎo", "english": "to guide; to direct", "category": "verb"},
    {"simplified": "追求", "traditional": "追求", "pinyin": "zhuī qiú", "english": "to pursue; to seek", "category": "verb"},
    {"simplified": "遵守", "traditional": "遵守", "pinyin": "zūn shǒu", "english": "to observe; to abide by", "category": "verb"},
    {"simplified": "组织", "traditional": "組織", "pinyin": "zǔ zhī", "english": "to organize; organization", "category": "verb"},
    {"simplified": "发展", "traditional": "發展", "pinyin": "fā zhǎn", "english": "to develop; development", "category": "verb"},
    {"simplified": "改革", "traditional": "改革", "pinyin": "gǎi gé", "english": "to reform; reform", "category": "verb"},
    {"simplified": "保护", "traditional": "保護", "pinyin": "bǎo hù", "english": "to protect; protection", "category": "verb"},
    {"simplified": "培养", "traditional": "培養", "pinyin": "péi yǎng", "english": "to cultivate; to train", "category": "verb"},
    {"simplified": "交流", "traditional": "交流", "pinyin": "jiāo liú", "english": "to exchange; communication", "category": "verb"},
    {"simplified": "沟通", "traditional": "溝通", "pinyin": "gōu tōng", "english": "to communicate", "category": "verb"},
    {"simplified": "表达", "traditional": "表達", "pinyin": "biǎo dá", "english": "to express", "category": "verb"},
    {"simplified": "传递", "traditional": "傳遞", "pinyin": "chuán dì", "english": "to convey; to pass on", "category": "verb"},
    {"simplified": "影响", "traditional": "影響", "pinyin": "yǐng xiǎng", "english": "to influence; influence", "category": "verb"},
    {"simplified": "吸引", "traditional": "吸引", "pinyin": "xī yǐn", "english": "to attract", "category": "verb"},
    {"simplified": "引起", "traditional": "引起", "pinyin": "yǐn qǐ", "english": "to cause; to give rise to", "category": "verb"},
    {"simplified": "包含", "traditional": "包含", "pinyin": "bāo hán", "english": "to contain; to include", "category": "verb"},
    {"simplified": "涉及", "traditional": "涉及", "pinyin": "shè jí", "english": "to involve; to relate to", "category": "verb"},
    {"simplified": "存在", "traditional": "存在", "pinyin": "cún zài", "english": "to exist; existence", "category": "verb"},
    {"simplified": "形成", "traditional": "形成", "pinyin": "xíng chéng", "english": "to form; to take shape", "category": "verb"},
    {"simplified": "构成", "traditional": "構成", "pinyin": "gòu chéng", "english": "to constitute; to compose", "category": "verb"},
    {"simplified": "反对", "traditional": "反對", "pinyin": "fǎn duì", "english": "to oppose; to object", "category": "verb"},
    {"simplified": "支持", "traditional": "支持", "pinyin": "zhī chí", "english": "to support; support", "category": "verb"},
    {"simplified": "赞成", "traditional": "贊成", "pinyin": "zàn chéng", "english": "to approve; to agree", "category": "verb"},
    {"simplified": "主张", "traditional": "主張", "pinyin": "zhǔ zhāng", "english": "to advocate; viewpoint", "category": "verb"},
    {"simplified": "坚持", "traditional": "堅持", "pinyin": "jiān chí", "english": "to persist; to insist", "category": "verb"},
    {"simplified": "放弃", "traditional": "放棄", "pinyin": "fàng qì", "english": "to give up; to abandon", "category": "verb"},
    {"simplified": "适应", "traditional": "適應", "pinyin": "shì yìng", "english": "to adapt; to adjust", "category": "verb"},
    {"simplified": "满足", "traditional": "滿足", "pinyin": "mǎn zú", "english": "to satisfy; satisfied", "category": "verb"},
    {"simplified": "集中", "traditional": "集中", "pinyin": "jí zhōng", "english": "to concentrate; to focus", "category": "verb"},
    {"simplified": "针对", "traditional": "針對", "pinyin": "zhēn duì", "english": "to target; aimed at", "category": "verb"},
    {"simplified": "依靠", "traditional": "依靠", "pinyin": "yī kào", "english": "to rely on; to depend on", "category": "verb"},
    {"simplified": "尊重", "traditional": "尊重", "pinyin": "zūn zhòng", "english": "to respect", "category": "verb"},
    {"simplified": "珍惜", "traditional": "珍惜", "pinyin": "zhēn xī", "english": "to cherish; to treasure", "category": "verb"},
    {"simplified": "牺牲", "traditional": "犧牲", "pinyin": "xī shēng", "english": "to sacrifice", "category": "verb"},
    {"simplified": "奉献", "traditional": "奉獻", "pinyin": "fèng xiàn", "english": "to devote; to dedicate", "category": "verb"},
    {"simplified": "挑战", "traditional": "挑戰", "pinyin": "tiǎo zhàn", "english": "to challenge; challenge", "category": "verb"},
    {"simplified": "奋斗", "traditional": "奮鬥", "pinyin": "fèn dòu", "english": "to strive; to struggle", "category": "verb"},
    {"simplified": "努力", "traditional": "努力", "pinyin": "nǔ lì", "english": "to work hard; effort", "category": "verb"},
    {"simplified": "争取", "traditional": "爭取", "pinyin": "zhēng qǔ", "english": "to fight for; to strive for", "category": "verb"},
    # ── Adjectives ──
    {"simplified": "巨大", "traditional": "巨大", "pinyin": "jù dà", "english": "huge; enormous", "category": "adjective"},
    {"simplified": "广泛", "traditional": "廣泛", "pinyin": "guǎng fàn", "english": "extensive; wide-ranging", "category": "adjective"},
    {"simplified": "深刻", "traditional": "深刻", "pinyin": "shēn kè", "english": "profound; deep", "category": "adjective"},
    {"simplified": "严峻", "traditional": "嚴峻", "pinyin": "yán jùn", "english": "severe; stern", "category": "adjective"},
    {"simplified": "复杂", "traditional": "複雜", "pinyin": "fù zá", "english": "complex; complicated", "category": "adjective"},
    {"simplified": "灵活", "traditional": "靈活", "pinyin": "líng huó", "english": "flexible; agile", "category": "adjective"},
    {"simplified": "适当", "traditional": "適當", "pinyin": "shì dàng", "english": "appropriate; proper", "category": "adjective"},
    {"simplified": "充足", "traditional": "充足", "pinyin": "chōng zú", "english": "sufficient; adequate", "category": "adjective"},
    {"simplified": "显著", "traditional": "顯著", "pinyin": "xiǎn zhù", "english": "notable; remarkable", "category": "adjective"},
    {"simplified": "稳定", "traditional": "穩定", "pinyin": "wěn dìng", "english": "stable; steady", "category": "adjective"},
    {"simplified": "持续", "traditional": "持續", "pinyin": "chí xù", "english": "continuous; sustained", "category": "adjective"},
    {"simplified": "具体", "traditional": "具體", "pinyin": "jù tǐ", "english": "concrete; specific", "category": "adjective"},
    {"simplified": "客观", "traditional": "客觀", "pinyin": "kè guān", "english": "objective", "category": "adjective"},
    {"simplified": "主观", "traditional": "主觀", "pinyin": "zhǔ guān", "english": "subjective", "category": "adjective"},
    {"simplified": "积极", "traditional": "積極", "pinyin": "jī jí", "english": "positive; active", "category": "adjective"},
    {"simplified": "消极", "traditional": "消極", "pinyin": "xiāo jí", "english": "negative; passive", "category": "adjective"},
    {"simplified": "合理", "traditional": "合理", "pinyin": "hé lǐ", "english": "reasonable; rational", "category": "adjective"},
    {"simplified": "有效", "traditional": "有效", "pinyin": "yǒu xiào", "english": "effective; valid", "category": "adjective"},
    {"simplified": "可靠", "traditional": "可靠", "pinyin": "kě kào", "english": "reliable; dependable", "category": "adjective"},
    {"simplified": "真实", "traditional": "真實", "pinyin": "zhēn shí", "english": "true; real", "category": "adjective"},
    {"simplified": "重大", "traditional": "重大", "pinyin": "zhòng dà", "english": "major; significant", "category": "adjective"},
    {"simplified": "关键", "traditional": "關鍵", "pinyin": "guān jiàn", "english": "key; crucial", "category": "adjective"},
    {"simplified": "突出", "traditional": "突出", "pinyin": "tū chū", "english": "prominent; outstanding", "category": "adjective"},
    {"simplified": "明确", "traditional": "明確", "pinyin": "míng què", "english": "clear; definite", "category": "adjective"},
    {"simplified": "典型", "traditional": "典型", "pinyin": "diǎn xíng", "english": "typical; representative", "category": "adjective"},
    {"simplified": "独特", "traditional": "獨特", "pinyin": "dú tè", "english": "unique; distinctive", "category": "adjective"},
    {"simplified": "宝贵", "traditional": "寶貴", "pinyin": "bǎo guì", "english": "precious; valuable", "category": "adjective"},
    {"simplified": "精彩", "traditional": "精彩", "pinyin": "jīng cǎi", "english": "brilliant; wonderful", "category": "adjective"},
    {"simplified": "乐观", "traditional": "樂觀", "pinyin": "lè guān", "english": "optimistic", "category": "adjective"},
    {"simplified": "悲观", "traditional": "悲觀", "pinyin": "bēi guān", "english": "pessimistic", "category": "adjective"},
    {"simplified": "敏感", "traditional": "敏感", "pinyin": "mǐn gǎn", "english": "sensitive", "category": "adjective"},
    {"simplified": "坚定", "traditional": "堅定", "pinyin": "jiān dìng", "english": "firm; resolute", "category": "adjective"},
    {"simplified": "勇敢", "traditional": "勇敢", "pinyin": "yǒng gǎn", "english": "brave; courageous", "category": "adjective"},
    {"simplified": "善良", "traditional": "善良", "pinyin": "shàn liáng", "english": "kind-hearted; good", "category": "adjective"},
    {"simplified": "诚实", "traditional": "誠實", "pinyin": "chéng shí", "english": "honest; sincere", "category": "adjective"},
    {"simplified": "谦虚", "traditional": "謙虛", "pinyin": "qiān xū", "english": "modest; humble", "category": "adjective"},
    {"simplified": "自信", "traditional": "自信", "pinyin": "zì xìn", "english": "self-confident", "category": "adjective"},
    {"simplified": "优秀", "traditional": "優秀", "pinyin": "yōu xiù", "english": "excellent; outstanding", "category": "adjective"},
    {"simplified": "丰富", "traditional": "豐富", "pinyin": "fēng fù", "english": "rich; abundant", "category": "adjective"},
    {"simplified": "严格", "traditional": "嚴格", "pinyin": "yán gé", "english": "strict; rigorous", "category": "adjective"},
    {"simplified": "认真", "traditional": "認真", "pinyin": "rèn zhēn", "english": "serious; conscientious", "category": "adjective"},
    {"simplified": "热情", "traditional": "熱情", "pinyin": "rè qíng", "english": "enthusiastic; warm", "category": "adjective"},
    {"simplified": "温暖", "traditional": "溫暖", "pinyin": "wēn nuǎn", "english": "warm", "category": "adjective"},
    {"simplified": "平等", "traditional": "平等", "pinyin": "píng děng", "english": "equal; equality", "category": "adjective"},
    {"simplified": "公平", "traditional": "公平", "pinyin": "gōng píng", "english": "fair; just", "category": "adjective"},
    {"simplified": "繁荣", "traditional": "繁榮", "pinyin": "fán róng", "english": "prosperous; thriving", "category": "adjective"},
    {"simplified": "必要", "traditional": "必要", "pinyin": "bì yào", "english": "necessary; essential", "category": "adjective"},
    {"simplified": "重要", "traditional": "重要", "pinyin": "zhòng yào", "english": "important", "category": "adjective"},
    {"simplified": "紧迫", "traditional": "緊迫", "pinyin": "jǐn pò", "english": "urgent; pressing", "category": "adjective"},
    {"simplified": "普遍", "traditional": "普遍", "pinyin": "pǔ biàn", "english": "universal; widespread", "category": "adjective"},
    {"simplified": "明显", "traditional": "明顯", "pinyin": "míng xiǎn", "english": "obvious; evident", "category": "adjective"},
    # ── Adverbs & Connectors ──
    {"simplified": "毕竟", "traditional": "畢竟", "pinyin": "bì jìng", "english": "after all; all in all", "category": "adverb"},
    {"simplified": "不禁", "traditional": "不禁", "pinyin": "bù jīn", "english": "can't help but", "category": "adverb"},
    {"simplified": "从而", "traditional": "從而", "pinyin": "cóng ér", "english": "thereby; thus", "category": "conjunction"},
    {"simplified": "根本", "traditional": "根本", "pinyin": "gēn běn", "english": "fundamentally; at all", "category": "adverb"},
    {"simplified": "简直", "traditional": "簡直", "pinyin": "jiǎn zhí", "english": "simply; absolutely", "category": "adverb"},
    {"simplified": "仅仅", "traditional": "僅僅", "pinyin": "jǐn jǐn", "english": "only; merely", "category": "adverb"},
    {"simplified": "尽管", "traditional": "儘管", "pinyin": "jǐn guǎn", "english": "despite; even though", "category": "conjunction"},
    {"simplified": "居然", "traditional": "居然", "pinyin": "jū rán", "english": "unexpectedly; to one's surprise", "category": "adverb"},
    {"simplified": "逐渐", "traditional": "逐漸", "pinyin": "zhú jiàn", "english": "gradually; step by step", "category": "adverb"},
    {"simplified": "终究", "traditional": "終究", "pinyin": "zhōng jiū", "english": "in the end; after all", "category": "adverb"},
    {"simplified": "总之", "traditional": "總之", "pinyin": "zǒng zhī", "english": "in a word; in short", "category": "adverb"},
    {"simplified": "始终", "traditional": "始終", "pinyin": "shǐ zhōng", "english": "from beginning to end; always", "category": "adverb"},
    {"simplified": "实际上", "traditional": "實際上", "pinyin": "shí jì shàng", "english": "in fact; actually", "category": "adverb"},
    {"simplified": "事实上", "traditional": "事實上", "pinyin": "shì shí shàng", "english": "in fact; as a matter of fact", "category": "adverb"},
    {"simplified": "随着", "traditional": "隨著", "pinyin": "suí zhe", "english": "along with; as", "category": "conjunction"},
    {"simplified": "相当", "traditional": "相當", "pinyin": "xiāng dāng", "english": "quite; considerably", "category": "adverb"},
    {"simplified": "以便", "traditional": "以便", "pinyin": "yǐ biàn", "english": "so that; in order to", "category": "conjunction"},
    {"simplified": "以免", "traditional": "以免", "pinyin": "yǐ miǎn", "english": "in order to avoid", "category": "conjunction"},
    {"simplified": "犹豫", "traditional": "猶豫", "pinyin": "yóu yù", "english": "to hesitate", "category": "adverb"},
    {"simplified": "反复", "traditional": "反復", "pinyin": "fǎn fù", "english": "repeatedly; again and again", "category": "adverb"},
    {"simplified": "分别", "traditional": "分別", "pinyin": "fēn bié", "english": "respectively; separately", "category": "adverb"},
    {"simplified": "果然", "traditional": "果然", "pinyin": "guǒ rán", "english": "as expected; sure enough", "category": "adverb"},
    {"simplified": "何况", "traditional": "何況", "pinyin": "hé kuàng", "english": "let alone; not to mention", "category": "conjunction"},
    {"simplified": "不免", "traditional": "不免", "pinyin": "bù miǎn", "english": "inevitably; unavoidably", "category": "adverb"},
    {"simplified": "大致", "traditional": "大致", "pinyin": "dà zhì", "english": "roughly; approximately", "category": "adverb"},
    {"simplified": "显然", "traditional": "顯然", "pinyin": "xiǎn rán", "english": "obviously; evidently", "category": "adverb"},
    {"simplified": "往往", "traditional": "往往", "pinyin": "wǎng wǎng", "english": "often; more often than not", "category": "adverb"},
    {"simplified": "无非", "traditional": "無非", "pinyin": "wú fēi", "english": "nothing but; simply", "category": "adverb"},
    {"simplified": "一度", "traditional": "一度", "pinyin": "yí dù", "english": "once; at one time", "category": "adverb"},
    {"simplified": "一再", "traditional": "一再", "pinyin": "yī zài", "english": "time and again; repeatedly", "category": "adverb"},
    {"simplified": "逐步", "traditional": "逐步", "pinyin": "zhú bù", "english": "step by step; progressively", "category": "adverb"},
    {"simplified": "不断", "traditional": "不斷", "pinyin": "bú duàn", "english": "continuously; unceasingly", "category": "adverb"},
    {"simplified": "不仅", "traditional": "不僅", "pinyin": "bù jǐn", "english": "not only", "category": "conjunction"},
    {"simplified": "曾经", "traditional": "曾經", "pinyin": "céng jīng", "english": "once; formerly", "category": "adverb"},
    {"simplified": "到底", "traditional": "到底", "pinyin": "dào dǐ", "english": "after all; in the end", "category": "adverb"},
    {"simplified": "然而", "traditional": "然而", "pinyin": "rán ér", "english": "however; yet", "category": "conjunction"},
    {"simplified": "因此", "traditional": "因此", "pinyin": "yīn cǐ", "english": "therefore; for this reason", "category": "conjunction"},
    {"simplified": "于是", "traditional": "於是", "pinyin": "yú shì", "english": "thereupon; consequently", "category": "conjunction"},
    {"simplified": "即使", "traditional": "即使", "pinyin": "jí shǐ", "english": "even if; even though", "category": "conjunction"},
    {"simplified": "无论", "traditional": "無論", "pinyin": "wú lùn", "english": "no matter; regardless", "category": "conjunction"},
    {"simplified": "不管", "traditional": "不管", "pinyin": "bù guǎn", "english": "no matter; regardless", "category": "conjunction"},
    {"simplified": "由于", "traditional": "由於", "pinyin": "yóu yú", "english": "due to; owing to", "category": "conjunction"},
    {"simplified": "既然", "traditional": "既然", "pinyin": "jì rán", "english": "since; given that", "category": "conjunction"},
    {"simplified": "另外", "traditional": "另外", "pinyin": "lìng wài", "english": "in addition; moreover", "category": "conjunction"},
    {"simplified": "此外", "traditional": "此外", "pinyin": "cǐ wài", "english": "besides; in addition", "category": "conjunction"},
    {"simplified": "总而言之", "traditional": "總而言之", "pinyin": "zǒng ér yán zhī", "english": "in summary; to sum up", "category": "conjunction"},
    # ── Idioms (Chengyu) ──
    {"simplified": "自相矛盾", "traditional": "自相矛盾", "pinyin": "zì xiāng máo dùn", "english": "self-contradictory", "category": "idiom"},
    {"simplified": "半途而废", "traditional": "半途而廢", "pinyin": "bàn tú ér fèi", "english": "to give up halfway", "category": "idiom"},
    {"simplified": "不可思议", "traditional": "不可思議", "pinyin": "bù kě sī yì", "english": "unimaginable; inconceivable", "category": "idiom"},
    {"simplified": "不知不觉", "traditional": "不知不覺", "pinyin": "bù zhī bù jué", "english": "unconsciously; unknowingly", "category": "idiom"},
    {"simplified": "大吃一惊", "traditional": "大吃一驚", "pinyin": "dà chī yī jīng", "english": "to be greatly surprised", "category": "idiom"},
    {"simplified": "各种各样", "traditional": "各種各樣", "pinyin": "gè zhǒng gè yàng", "english": "all kinds of; various", "category": "idiom"},
    {"simplified": "理所当然", "traditional": "理所當然", "pinyin": "lǐ suǒ dāng rán", "english": "as a matter of course; natural", "category": "idiom"},
    {"simplified": "迫不及待", "traditional": "迫不及待", "pinyin": "pò bù jí dài", "english": "unable to wait; impatient", "category": "idiom"},
    {"simplified": "千方百计", "traditional": "千方百計", "pinyin": "qiān fāng bǎi jì", "english": "by every possible means", "category": "idiom"},
    {"simplified": "情不自禁", "traditional": "情不自禁", "pinyin": "qíng bù zì jīn", "english": "unable to restrain oneself", "category": "idiom"},
    {"simplified": "全力以赴", "traditional": "全力以赴", "pinyin": "quán lì yǐ fù", "english": "to go all out", "category": "idiom"},
    {"simplified": "日新月异", "traditional": "日新月異", "pinyin": "rì xīn yuè yì", "english": "changing rapidly", "category": "idiom"},
    {"simplified": "实事求是", "traditional": "實事求是", "pinyin": "shí shì qiú shì", "english": "to seek truth from facts", "category": "idiom"},
    {"simplified": "无可奈何", "traditional": "無可奈何", "pinyin": "wú kě nài hé", "english": "helpless; having no choice", "category": "idiom"},
    {"simplified": "与众不同", "traditional": "與眾不同", "pinyin": "yǔ zhòng bù tóng", "english": "different from others; unique", "category": "idiom"},
    {"simplified": "自言自语", "traditional": "自言自語", "pinyin": "zì yán zì yǔ", "english": "to talk to oneself", "category": "idiom"},
    {"simplified": "刻不容缓", "traditional": "刻不容緩", "pinyin": "kè bù róng huǎn", "english": "extremely urgent; pressing", "category": "idiom"},
    {"simplified": "名副其实", "traditional": "名副其實", "pinyin": "míng fù qí shí", "english": "to live up to one's name", "category": "idiom"},
    {"simplified": "前所未有", "traditional": "前所未有", "pinyin": "qián suǒ wèi yǒu", "english": "unprecedented", "category": "idiom"},
    {"simplified": "任重道远", "traditional": "任重道遠", "pinyin": "rèn zhòng dào yuǎn", "english": "heavy responsibility and long road", "category": "idiom"},
    {"simplified": "深思熟虑", "traditional": "深思熟慮", "pinyin": "shēn sī shú lǜ", "english": "to think carefully; deliberate", "category": "idiom"},
    {"simplified": "脱颖而出", "traditional": "脫穎而出", "pinyin": "tuō yǐng ér chū", "english": "to stand out; to emerge", "category": "idiom"},
    {"simplified": "众所周知", "traditional": "眾所周知", "pinyin": "zhòng suǒ zhōu zhī", "english": "as everyone knows", "category": "idiom"},
    {"simplified": "一帆风顺", "traditional": "一帆風順", "pinyin": "yī fān fēng shùn", "english": "smooth sailing", "category": "idiom"},
    {"simplified": "引人注目", "traditional": "引人注目", "pinyin": "yǐn rén zhù mù", "english": "eye-catching; attention-grabbing", "category": "idiom"},
    {"simplified": "源远流长", "traditional": "源遠流長", "pinyin": "yuán yuǎn liú cháng", "english": "having a long history", "category": "idiom"},
]

def seed_hsk5():
    db = SessionLocal()
    try:
        existing = db.query(HanziWord).filter(HanziWord.hsk_level == 5).all()
        existing_simplified = {w.simplified for w in existing}

        added = 0
        for w in hsk5_words:
            if w["simplified"] not in existing_simplified:
                word = HanziWord(
                    simplified=w["simplified"],
                    traditional=w["traditional"],
                    pinyin=w["pinyin"],
                    english=w["english"],
                    hsk_level=5,
                    category=w.get("category")
                )
                db.add(word)
                added += 1

        db.commit()
        print(f"HSK 5: Added {added} new words (already had {len(existing_simplified)})")
    except Exception as e:
        print(f"Error: {e}")
        db.rollback()
    finally:
        db.close()

if __name__ == "__main__":
    seed_hsk5()
