"""
Complete HSK 1 vocabulary - 268 characters
Run this to populate database with full HSK 1 vocabulary
"""

from app.database import SessionLocal
from app.models import HanziWord

# Complete HSK 1 vocabulary data (268 characters)
hsk1_complete = [
    # Characters from reference (WriteHanzi)
    ("请", "请", "qǐng", "please; to request"),
    ("写", "写", "xiě", "to write"),
    ("明", "明", "míng", "bright; clear; tomorrow"),
    ("人", "人", "rén", "person; people"),
    ("孩", "孩", "hái", "child"),
    ("电", "電", "diàn", "electricity; electric"),
    ("觉", "覺", "jué", "to feel; to think"),
    ("开", "開", "kāi", "to open; to start"),
    ("玩", "玩", "wán", "to play; to have fun"),
    ("客", "客", "kè", "guest; customer"),
    ("对", "對", "duì", "correct; right; to face"),
    ("个", "個", "gè", "measure word (general)"),
    ("来", "來", "lái", "to come"),
    ("图", "圖", "tú", "picture; map"),
    ("从", "從", "cóng", "from"),
    ("您", "您", "nín", "you (polite)"),
    ("想", "想", "xiǎng", "to think; to want"),
    ("怎", "怎", "zěn", "how"),
    ("三", "三", "sān", "three"),
    ("读", "讀", "dú", "to read"),
    ("干", "幹", "gàn", "to do; dry"),
    ("毛", "毛", "máo", "hair; feather"),
    ("现", "現", "xiàn", "now; present"),
    ("息", "息", "xī", "breath; to rest"),
    ("二", "二", "èr", "two"),
    ("错", "錯", "cuò", "wrong; mistake"),
    ("门", "門", "mén", "door; gate"),
    ("找", "找", "zhǎo", "to look for; to find"),
    ("远", "遠", "yuǎn", "far; distant"),
    ("东", "東", "dōng", "east"),
    ("老", "老", "lǎo", "old"),
    ("月", "月", "yuè", "month; moon"),
    ("医", "醫", "yī", "doctor; medicine"),
    ("儿", "兒", "ér", "child; son"),
    ("有", "有", "yǒu", "to have"),
    ("早", "早", "zǎo", "early; morning"),
    ("试", "試", "shì", "to try; test"),
    ("谢", "謝", "xiè", "to thank"),
    ("他", "他", "tā", "he; him"),
    ("店", "店", "diàn", "shop; store"),
    ("们", "們", "men", "plural suffix"),
    ("喜", "喜", "xǐ", "to like; happy"),
    ("很", "很", "hěn", "very"),
    ("到", "到", "dào", "to arrive; to reach"),
    ("友", "友", "yǒu", "friend"),
    ("院", "院", "yuàn", "yard; institution"),
    ("她", "她", "tā", "she; her"),
    ("日", "日", "rì", "sun; day"),
    ("病", "病", "bìng", "illness; sick"),
    ("路", "路", "lù", "road; path"),
    ("再", "再", "zài", "again"),
    ("真", "真", "zhēn", "true; real"),
    ("肉", "肉", "ròu", "meat"),
    ("非", "非", "fēi", "not; wrong"),
    ("五", "五", "wǔ", "five"),
    ("南", "南", "nán", "south"),
    ("小", "小", "xiǎo", "small; little"),
    ("水", "水", "shuǐ", "water"),
    ("买", "買", "mǎi", "to buy"),
    ("冷", "冷", "lěng", "cold"),
    ("等", "等", "děng", "to wait; etc."),
    ("蛋", "蛋", "dàn", "egg"),
    ("菜", "菜", "cài", "vegetable; dish"),
    ("家", "家", "jiā", "home; family"),
    ("饭", "飯", "fàn", "cooked rice; meal"),
    ("能", "能", "néng", "can; able"),
    ("也", "也", "yě", "also; too"),
    ("谁", "誰", "shuí", "who"),
    ("妈", "媽", "mā", "mom; mother"),
    ("年", "年", "nián", "year"),
    ("四", "四", "sì", "four"),
    ("道", "道", "dào", "way; road"),
    ("旁", "旁", "páng", "beside; side"),
    ("衣", "衣", "yī", "clothes"),
    ("班", "班", "bān", "class; team"),
    ("知", "知", "zhī", "to know"),
    ("妹", "妹", "mèi", "younger sister"),
    ("哥", "哥", "gē", "older brother"),
    ("口", "口", "kǒu", "mouth"),
    ("样", "樣", "yàng", "appearance; kind"),
    ("问", "問", "wèn", "to ask"),
    ("弟", "弟", "dì", "younger brother"),
    ("杯", "杯", "bēi", "cup; glass"),
    ("天", "天", "tiān", "sky; day; heaven"),
    ("唱", "唱", "chàng", "to sing"),
    ("岁", "歲", "suì", "year (of age)"),
    ("忘", "忘", "wàng", "to forget"),
    ("页", "頁", "yè", "page"),
    ("七", "七", "qī", "seven"),
    ("汽", "汽", "qì", "steam; gas"),
    ("名", "名", "míng", "name"),
    ("左", "左", "zuǒ", "left"),
    ("球", "球", "qiú", "ball"),
    ("方", "方", "fāng", "square; direction"),
    ("饿", "餓", "è", "hungry"),
    ("洗", "洗", "xǐ", "to wash"),
    ("面", "面", "miàn", "face; noodles"),
    ("花", "花", "huā", "flower"),
    ("体", "體", "tǐ", "body"),
    ("飞", "飛", "fēi", "to fly"),
    ("火", "火", "huǒ", "fire"),
    ("穿", "穿", "chuān", "to wear; to put on"),
    ("米", "米", "mǐ", "rice; meter"),
    ("次", "次", "cì", "time; occurrence"),
    ("本", "本", "běn", "root; book; measure word"),
    ("同", "同", "tóng", "same; together"),
    ("忙", "忙", "máng", "busy"),
    ("时", "時", "shí", "time; hour"),
    ("票", "票", "piào", "ticket"),
    ("女", "女", "nǚ", "woman; female"),
    ("歌", "歌", "gē", "song"),
    ("爸", "爸", "bà", "dad; father"),
    ("慢", "慢", "màn", "slow"),
    ("点", "點", "diǎn", "point; o'clock"),
    ("那", "那", "nà", "that"),
    ("进", "進", "jìn", "to enter"),
    ("跟", "跟", "gēn", "with; to follow"),
    ("午", "午", "wǔ", "noon"),
    ("正", "正", "zhèng", "just; correct"),
    ("事", "事", "shì", "matter; thing"),
    ("备", "備", "bèi", "to prepare"),
    ("识", "識", "shí", "to know; knowledge"),
    ("号", "號", "hào", "number; mark"),
    ("睡", "睡", "shuì", "to sleep"),
    ("站", "站", "zhàn", "station; to stand"),
    ("休", "休", "xiū", "to rest"),
    ("山", "山", "shān", "mountain; hill"),
    ("百", "百", "bǎi", "hundred"),
    ("帮", "幫", "bāng", "to help"),
    ("作", "作", "zuò", "to do; to make; work"),
    ("用", "用", "yòng", "to use"),
    ("拿", "拿", "ná", "to take; to hold"),
    ("边", "邊", "biān", "side; edge"),
    ("常", "常", "cháng", "often; common"),
    ("听", "聽", "tīng", "to listen"),
    ("包", "包", "bāo", "bag; to wrap"),
    ("还", "還", "hái", "still; also; to return"),
    ("果", "果", "guǒ", "fruit; result"),
    ("见", "見", "jiàn", "to see; to meet"),
    ("吃", "吃", "chī", "to eat"),
    ("呢", "呢", "ne", "question particle"),
    ("白", "白", "bái", "white"),
    ("汉", "漢", "hàn", "Han (Chinese); man"),
    ("不", "不", "bù", "not; no"),
    ("认", "認", "rèn", "to recognize"),
    ("最", "最", "zuì", "most; very"),
    ("爷", "爺", "yé", "grandfather"),
    ("星", "星", "xīng", "star"),
    ("今", "今", "jīn", "today; now"),
    ("欢", "歡", "huān", "happy; joyous"),
    ("机", "機", "jī", "machine"),
    ("放", "放", "fàng", "to put; to release"),
    ("热", "熱", "rè", "hot"),
    ("网", "網", "wǎng", "net; network"),
    ("条", "條", "tiáo", "strip; measure word"),
    ("前", "前", "qián", "front; before"),
    ("钱", "錢", "qián", "money"),
    ("字", "字", "zì", "character; word"),
    ("坏", "壞", "huài", "bad; broken"),
    ("元", "元", "yuán", "yuan (currency)"),
    ("习", "習", "xí", "to practice; to study"),
    ("诉", "訴", "sù", "to tell; to complain"),
    ("准", "準", "zhǔn", "accurate; to allow"),
    ("鸡", "雞", "jī", "chicken"),
    ("桌", "桌", "zhuō", "table; desk"),
    ("一", "一", "yī", "one"),
    ("第", "第", "dì", "prefix for ordinal numbers"),
    ("工", "工", "gōng", "work; worker"),
    ("后", "後", "hòu", "after; behind"),
    ("跑", "跑", "pǎo", "to run"),
    ("话", "話", "huà", "words; language"),
    ("渴", "渴", "kě", "thirsty"),
    ("贵", "貴", "guì", "expensive; noble"),
    ("动", "動", "dòng", "to move"),
    ("楼", "樓", "lóu", "building; floor"),
    ("介", "介", "jiè", "to introduce; between"),
    ("生", "生", "shēng", "to give birth; life; to live"),
    ("就", "就", "jiù", "at once; then"),
    ("高", "高", "gāo", "tall; high"),
    ("六", "六", "liù", "six"),
    ("好", "好", "hǎo", "good; well"),
    ("影", "影", "yǐng", "shadow; image"),
    ("床", "床", "chuáng", "bed"),
    ("身", "身", "shēn", "body"),
    ("场", "場", "chǎng", "field; place"),
    ("课", "課", "kè", "lesson; class"),
    ("校", "校", "xiào", "school"),
    ("起", "起", "qǐ", "to rise; to start"),
    ("西", "西", "xī", "west"),
    ("半", "半", "bàn", "half"),
    ("商", "商", "shāng", "commerce; merchant"),
    ("昨", "昨", "zuó", "yesterday"),
    ("吗", "嗎", "ma", "question particle"),
    ("这", "這", "zhè", "this"),
    ("牛", "牛", "niú", "cow; ox"),
    ("去", "去", "qù", "to go"),
    ("车", "車", "chē", "car; vehicle"),
    ("块", "塊", "kuài", "piece; yuan (measure)"),
    ("零", "零", "líng", "zero"),
    ("记", "記", "jì", "to remember; to record"),
    ("太", "太", "tài", "too; very"),
    ("服", "服", "fú", "clothes; to serve"),
    ("绍", "紹", "shào", "to continue; to introduce"),
    ("教", "教", "jiào", "to teach"),
    ("爱", "愛", "ài", "to love"),
    ("我", "我", "wǒ", "I; me"),
    ("叫", "叫", "jiào", "to call; to be called"),
    ("师", "師", "shī", "teacher; master"),
    ("文", "文", "wén", "writing; culture"),
    ("笑", "笑", "xiào", "to laugh; to smile"),
    ("雨", "雨", "yǔ", "rain"),
    ("十", "十", "shí", "ten"),
    ("出", "出", "chū", "to go out"),
    ("书", "書", "shū", "book"),
    ("做", "做", "zuò", "to do; to make"),
    ("在", "在", "zài", "at; in; to exist"),
    ("男", "男", "nán", "male; man"),
    ("风", "風", "fēng", "wind"),
    ("姐", "姐", "jiě", "older sister"),
    ("净", "淨", "jìng", "clean; pure"),
    ("奶", "奶", "nǎi", "milk; breast"),
    ("考", "考", "kǎo", "to test; exam"),
    ("马", "馬", "mǎ", "horse"),
    ("坐", "坐", "zuò", "to sit"),
    ("些", "些", "xiē", "some; a few"),
    ("你", "你", "nǐ", "you"),
    ("什", "什", "shí", "what"),
    ("是", "是", "shì", "to be; yes"),
    ("两", "兩", "liǎng", "two; both"),
    ("走", "走", "zǒu", "to walk; to go"),
    ("关", "關", "guān", "to close; to turn off"),
    ("住", "住", "zhù", "to live; to stay"),
    ("期", "期", "qī", "period; to expect"),
    ("下", "下", "xià", "down; below; next"),
    ("气", "氣", "qì", "air; gas; breath"),
    ("馆", "館", "guǎn", "building; shop;館"),
    ("上", "上", "shàng", "up; above; on"),
    ("晚", "晚", "wǎn", "late; evening"),
    ("里", "裡", "lǐ", "inside; in"),
    ("回", "回", "huí", "to return; back"),
    ("学", "學", "xué", "to study; to learn"),
    ("快", "快", "kuài", "fast; quick"),
    ("右", "右", "yòu", "right"),
    ("视", "視", "shì", "to look at; to view"),
    ("北", "北", "běi", "north"),
    ("茶", "茶", "chá", "tea"),
    ("先", "先", "xiān", "first; before"),
    ("候", "候", "hòu", "to wait; time"),
    ("告", "告", "gào", "to tell; to inform"),
    ("外", "外", "wài", "outside; foreign"),
    ("新", "新", "xīn", "new"),
    ("语", "語", "yǔ", "language; words"),
    ("地", "地", "dì", "earth; ground"),
    ("朋", "朋", "péng", "friend"),
    ("说", "說", "shuō", "to say; to speak"),
    ("九", "九", "jiǔ", "nine"),
    ("树", "樹", "shù", "tree"),
    ("送", "送", "sòng", "to send; to give"),
    ("比", "比", "bǐ", "to compare"),
    ("房", "房", "fáng", "house; room"),
    ("子", "子", "zǐ", "child; son; suffix"),
    ("多", "多", "duō", "many; much; more"),
    ("国", "國", "guó", "country; nation"),
    ("么", "麼", "me", "suffix"),
    ("手", "手", "shǒu", "hand"),
    ("京", "京", "jīng", "capital city"),
    ("脑", "腦", "nǎo", "brain"),
    ("八", "八", "bā", "eight"),
    ("的", "的", "de", "possessive particle"),
    ("中", "中", "zhōng", "middle; center; China"),
]


def seed_hsk1_complete():
    """Add complete HSK 1 vocabulary to database"""
    db = SessionLocal()
    try:
        print("Starting HSK 1 complete vocabulary seeding...")

        # Get existing words to avoid duplicates
        existing = db.query(HanziWord).filter(HanziWord.hsk_level == 1).all()
        existing_simplified = {w.simplified for w in existing}

        added_count = 0
        skipped_count = 0

        for simplified, traditional, pinyin, english in hsk1_complete:
            if simplified in existing_simplified:
                skipped_count += 1
                continue

            word = HanziWord(
                simplified=simplified,
                traditional=traditional,
                pinyin=pinyin,
                english=english,
                hsk_level=1
            )
            db.add(word)
            added_count += 1

        db.commit()

        print(f"\n[SUCCESS] HSK 1 Complete Seeding Done!")
        print(f"  Added: {added_count} new words")
        print(f"  Skipped: {skipped_count} existing words")
        print(f"  Total HSK 1 words in database: {added_count + skipped_count}")

    except Exception as e:
        print(f"Error seeding HSK 1: {e}")
        db.rollback()
    finally:
        db.close()


if __name__ == "__main__":
    seed_hsk1_complete()
