"""
Complete HSK 4 vocabulary - ~600 words
Based on official HSK 4.0 word list
"""
import sys
import io
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

from app.database import SessionLocal
from app.models import HanziWord

hsk4_words = [
    # ============================================================
    # NOUNS (~180 words)
    # ============================================================

    # --- People & Relationships ---
    {"simplified": "丈夫", "traditional": "丈夫", "pinyin": "zhàng fu", "english": "husband", "category": "noun"},
    {"simplified": "妻子", "traditional": "妻子", "pinyin": "qī zi", "english": "wife", "category": "noun"},
    {"simplified": "儿童", "traditional": "兒童", "pinyin": "ér tóng", "english": "children", "category": "noun"},
    {"simplified": "老板", "traditional": "老闆", "pinyin": "lǎo bǎn", "english": "boss; employer", "category": "noun"},
    {"simplified": "同事", "traditional": "同事", "pinyin": "tóng shì", "english": "colleague; coworker", "category": "noun"},
    {"simplified": "律师", "traditional": "律師", "pinyin": "lǜ shī", "english": "lawyer; attorney", "category": "noun"},
    {"simplified": "教授", "traditional": "教授", "pinyin": "jiào shòu", "english": "professor", "category": "noun"},
    {"simplified": "博士", "traditional": "博士", "pinyin": "bó shì", "english": "doctor (PhD); doctoral degree", "category": "noun"},
    {"simplified": "导游", "traditional": "導遊", "pinyin": "dǎo yóu", "english": "tour guide", "category": "noun"},
    {"simplified": "厨师", "traditional": "廚師", "pinyin": "chú shī", "english": "cook; chef", "category": "noun"},
    {"simplified": "顾客", "traditional": "顧客", "pinyin": "gù kè", "english": "customer; client", "category": "noun"},
    {"simplified": "观众", "traditional": "觀眾", "pinyin": "guān zhòng", "english": "audience; spectator", "category": "noun"},
    {"simplified": "乘客", "traditional": "乘客", "pinyin": "chéng kè", "english": "passenger", "category": "noun"},
    {"simplified": "邻居", "traditional": "鄰居", "pinyin": "lín jū", "english": "neighbor", "category": "noun"},
    {"simplified": "亲戚", "traditional": "親戚", "pinyin": "qīn qi", "english": "relative; family member", "category": "noun"},
    {"simplified": "对象", "traditional": "對象", "pinyin": "duì xiàng", "english": "target; partner; boyfriend/girlfriend", "category": "noun"},
    {"simplified": "对手", "traditional": "對手", "pinyin": "duì shǒu", "english": "opponent; rival", "category": "noun"},
    {"simplified": "人才", "traditional": "人才", "pinyin": "rén cái", "english": "talent; talented person", "category": "noun"},
    {"simplified": "人物", "traditional": "人物", "pinyin": "rén wù", "english": "character; figure; personage", "category": "noun"},
    {"simplified": "青少年", "traditional": "青少年", "pinyin": "qīng shào nián", "english": "teenager; youth", "category": "noun"},
    {"simplified": "主人", "traditional": "主人", "pinyin": "zhǔ rén", "english": "host; owner; master", "category": "noun"},
    {"simplified": "作者", "traditional": "作者", "pinyin": "zuò zhě", "english": "author; writer", "category": "noun"},

    # --- Emotions, Thoughts & Abstract ---
    {"simplified": "理想", "traditional": "理想", "pinyin": "lǐ xiǎng", "english": "ideal; dream", "category": "noun"},
    {"simplified": "责任", "traditional": "責任", "pinyin": "zé rèn", "english": "responsibility; duty", "category": "noun"},
    {"simplified": "效果", "traditional": "效果", "pinyin": "xiào guǒ", "english": "effect; result", "category": "noun"},
    {"simplified": "态度", "traditional": "態度", "pinyin": "tài du", "english": "attitude; manner", "category": "noun"},
    {"simplified": "感情", "traditional": "感情", "pinyin": "gǎn qíng", "english": "feeling; emotion; affection", "category": "noun"},
    {"simplified": "印象", "traditional": "印象", "pinyin": "yìn xiàng", "english": "impression", "category": "noun"},
    {"simplified": "表情", "traditional": "表情", "pinyin": "biǎo qíng", "english": "facial expression", "category": "noun"},
    {"simplified": "情况", "traditional": "情況", "pinyin": "qíng kuàng", "english": "situation; condition", "category": "noun"},
    {"simplified": "状况", "traditional": "狀況", "pinyin": "zhuàng kuàng", "english": "condition; state; situation", "category": "noun"},
    {"simplified": "原因", "traditional": "原因", "pinyin": "yuán yīn", "english": "cause; reason", "category": "noun"},
    {"simplified": "理由", "traditional": "理由", "pinyin": "lǐ yóu", "english": "reason; justification", "category": "noun"},
    {"simplified": "目的", "traditional": "目的", "pinyin": "mù dì", "english": "purpose; aim; goal", "category": "noun"},
    {"simplified": "结论", "traditional": "結論", "pinyin": "jié lùn", "english": "conclusion", "category": "noun"},
    {"simplified": "概念", "traditional": "概念", "pinyin": "gài niàn", "english": "concept; notion", "category": "noun"},
    {"simplified": "基础", "traditional": "基礎", "pinyin": "jī chǔ", "english": "foundation; basis", "category": "noun"},
    {"simplified": "道理", "traditional": "道理", "pinyin": "dào li", "english": "reason; principle; truth", "category": "noun"},
    {"simplified": "风格", "traditional": "風格", "pinyin": "fēng gé", "english": "style; manner", "category": "noun"},
    {"simplified": "特点", "traditional": "特點", "pinyin": "tè diǎn", "english": "characteristic; feature", "category": "noun"},
    {"simplified": "优点", "traditional": "優點", "pinyin": "yōu diǎn", "english": "advantage; merit; strong point", "category": "noun"},
    {"simplified": "缺点", "traditional": "缺點", "pinyin": "quē diǎn", "english": "shortcoming; defect; weakness", "category": "noun"},
    {"simplified": "区别", "traditional": "區別", "pinyin": "qū bié", "english": "difference; distinction", "category": "noun"},
    {"simplified": "联系", "traditional": "聯繫", "pinyin": "lián xì", "english": "connection; contact", "category": "noun"},
    {"simplified": "作用", "traditional": "作用", "pinyin": "zuò yòng", "english": "function; role; effect", "category": "noun"},
    {"simplified": "地位", "traditional": "地位", "pinyin": "dì wèi", "english": "status; position", "category": "noun"},
    {"simplified": "身份", "traditional": "身份", "pinyin": "shēn fèn", "english": "identity; status", "category": "noun"},
    {"simplified": "背景", "traditional": "背景", "pinyin": "bèi jǐng", "english": "background; context", "category": "noun"},
    {"simplified": "范围", "traditional": "範圍", "pinyin": "fàn wéi", "english": "scope; range; extent", "category": "noun"},
    {"simplified": "程度", "traditional": "程度", "pinyin": "chéng dù", "english": "degree; level; extent", "category": "noun"},
    {"simplified": "比例", "traditional": "比例", "pinyin": "bǐ lì", "english": "proportion; ratio; scale", "category": "noun"},
    {"simplified": "效率", "traditional": "效率", "pinyin": "xiào lǜ", "english": "efficiency", "category": "noun"},
    {"simplified": "规律", "traditional": "規律", "pinyin": "guī lǜ", "english": "law; regular pattern", "category": "noun"},
    {"simplified": "现象", "traditional": "現象", "pinyin": "xiàn xiàng", "english": "phenomenon", "category": "noun"},
    {"simplified": "事实", "traditional": "事實", "pinyin": "shì shí", "english": "fact; reality", "category": "noun"},
    {"simplified": "证据", "traditional": "證據", "pinyin": "zhèng jù", "english": "evidence; proof", "category": "noun"},

    # --- Business, Economy & Society ---
    {"simplified": "材料", "traditional": "材料", "pinyin": "cái liào", "english": "material; data", "category": "noun"},
    {"simplified": "资源", "traditional": "資源", "pinyin": "zī yuán", "english": "resources", "category": "noun"},
    {"simplified": "能源", "traditional": "能源", "pinyin": "néng yuán", "english": "energy; energy source", "category": "noun"},
    {"simplified": "产品", "traditional": "產品", "pinyin": "chǎn pǐn", "english": "product; goods", "category": "noun"},
    {"simplified": "商品", "traditional": "商品", "pinyin": "shāng pǐn", "english": "commodity; merchandise", "category": "noun"},
    {"simplified": "贸易", "traditional": "貿易", "pinyin": "mào yì", "english": "trade; commerce", "category": "noun"},
    {"simplified": "利润", "traditional": "利潤", "pinyin": "lì rùn", "english": "profit", "category": "noun"},
    {"simplified": "费用", "traditional": "費用", "pinyin": "fèi yòng", "english": "cost; expense; fee", "category": "noun"},
    {"simplified": "工资", "traditional": "工資", "pinyin": "gōng zī", "english": "salary; wages", "category": "noun"},
    {"simplified": "收入", "traditional": "收入", "pinyin": "shōu rù", "english": "income; revenue", "category": "noun"},
    {"simplified": "制度", "traditional": "制度", "pinyin": "zhì dù", "english": "system; institution", "category": "noun"},
    {"simplified": "政策", "traditional": "政策", "pinyin": "zhèng cè", "english": "policy", "category": "noun"},
    {"simplified": "法律", "traditional": "法律", "pinyin": "fǎ lǜ", "english": "law; legislation", "category": "noun"},
    {"simplified": "规定", "traditional": "規定", "pinyin": "guī dìng", "english": "regulation; rule; provision", "category": "noun"},
    {"simplified": "权利", "traditional": "權利", "pinyin": "quán lì", "english": "right; privilege", "category": "noun"},
    {"simplified": "任务", "traditional": "任務", "pinyin": "rèn wu", "english": "task; mission; assignment", "category": "noun"},
    {"simplified": "困难", "traditional": "困難", "pinyin": "kùn nan", "english": "difficulty; hardship", "category": "noun"},
    {"simplified": "压力", "traditional": "壓力", "pinyin": "yā lì", "english": "pressure; stress", "category": "noun"},
    {"simplified": "危险", "traditional": "危險", "pinyin": "wēi xiǎn", "english": "danger; risk", "category": "noun"},
    {"simplified": "行业", "traditional": "行業", "pinyin": "háng yè", "english": "industry; profession", "category": "noun"},
    {"simplified": "市场", "traditional": "市場", "pinyin": "shì chǎng", "english": "market; marketplace", "category": "noun"},
    {"simplified": "经济", "traditional": "經濟", "pinyin": "jīng jì", "english": "economy; economics", "category": "noun"},
    {"simplified": "经验", "traditional": "經驗", "pinyin": "jīng yàn", "english": "experience", "category": "noun"},
    {"simplified": "广告", "traditional": "廣告", "pinyin": "guǎng gào", "english": "advertisement", "category": "noun"},
    {"simplified": "竞争", "traditional": "競爭", "pinyin": "jìng zhēng", "english": "competition", "category": "noun"},

    # --- Science, Technology & Information ---
    {"simplified": "网络", "traditional": "網絡", "pinyin": "wǎng luò", "english": "network; internet", "category": "noun"},
    {"simplified": "系统", "traditional": "系統", "pinyin": "xì tǒng", "english": "system", "category": "noun"},
    {"simplified": "程序", "traditional": "程序", "pinyin": "chéng xù", "english": "procedure; program", "category": "noun"},
    {"simplified": "文件", "traditional": "文件", "pinyin": "wén jiàn", "english": "document; file", "category": "noun"},
    {"simplified": "消息", "traditional": "消息", "pinyin": "xiāo xi", "english": "news; message; information", "category": "noun"},
    {"simplified": "信息", "traditional": "信息", "pinyin": "xìn xī", "english": "information; message", "category": "noun"},
    {"simplified": "资料", "traditional": "資料", "pinyin": "zī liào", "english": "data; material; information", "category": "noun"},
    {"simplified": "数据", "traditional": "數據", "pinyin": "shù jù", "english": "data; statistics", "category": "noun"},
    {"simplified": "技术", "traditional": "技術", "pinyin": "jì shù", "english": "technology; technique; skill", "category": "noun"},
    {"simplified": "科学", "traditional": "科學", "pinyin": "kē xué", "english": "science; scientific", "category": "noun"},

    # --- Measurement & Quantity ---
    {"simplified": "质量", "traditional": "質量", "pinyin": "zhì liàng", "english": "quality; mass", "category": "noun"},
    {"simplified": "数量", "traditional": "數量", "pinyin": "shù liàng", "english": "quantity; amount", "category": "noun"},
    {"simplified": "长度", "traditional": "長度", "pinyin": "cháng dù", "english": "length", "category": "noun"},
    {"simplified": "面积", "traditional": "面積", "pinyin": "miàn jī", "english": "area; surface area", "category": "noun"},
    {"simplified": "重量", "traditional": "重量", "pinyin": "zhòng liàng", "english": "weight", "category": "noun"},
    {"simplified": "速度", "traditional": "速度", "pinyin": "sù dù", "english": "speed; velocity", "category": "noun"},
    {"simplified": "温度", "traditional": "溫度", "pinyin": "wēn dù", "english": "temperature", "category": "noun"},

    # --- Nature & Environment ---
    {"simplified": "气候", "traditional": "氣候", "pinyin": "qì hòu", "english": "climate", "category": "noun"},
    {"simplified": "污染", "traditional": "污染", "pinyin": "wū rǎn", "english": "pollution; contamination", "category": "noun"},
    {"simplified": "垃圾", "traditional": "垃圾", "pinyin": "lā jī", "english": "garbage; trash; rubbish", "category": "noun"},
    {"simplified": "环境", "traditional": "環境", "pinyin": "huán jìng", "english": "environment; surroundings", "category": "noun"},
    {"simplified": "自然", "traditional": "自然", "pinyin": "zì rán", "english": "nature; natural", "category": "noun"},
    {"simplified": "空气", "traditional": "空氣", "pinyin": "kōng qì", "english": "air; atmosphere", "category": "noun"},
    {"simplified": "阳光", "traditional": "陽光", "pinyin": "yáng guāng", "english": "sunlight; sunshine", "category": "noun"},
    {"simplified": "沙漠", "traditional": "沙漠", "pinyin": "shā mò", "english": "desert", "category": "noun"},
    {"simplified": "海洋", "traditional": "海洋", "pinyin": "hǎi yáng", "english": "ocean; sea", "category": "noun"},
    {"simplified": "陆地", "traditional": "陸地", "pinyin": "lù dì", "english": "land; dry land", "category": "noun"},
    {"simplified": "平原", "traditional": "平原", "pinyin": "píng yuán", "english": "plain; flatland", "category": "noun"},
    {"simplified": "森林", "traditional": "森林", "pinyin": "sēn lín", "english": "forest", "category": "noun"},

    # --- Education & Culture ---
    {"simplified": "知识", "traditional": "知識", "pinyin": "zhī shi", "english": "knowledge", "category": "noun"},
    {"simplified": "学问", "traditional": "學問", "pinyin": "xué wen", "english": "learning; knowledge; scholarship", "category": "noun"},
    {"simplified": "文化", "traditional": "文化", "pinyin": "wén huà", "english": "culture; civilization", "category": "noun"},
    {"simplified": "文学", "traditional": "文學", "pinyin": "wén xué", "english": "literature", "category": "noun"},
    {"simplified": "艺术", "traditional": "藝術", "pinyin": "yì shù", "english": "art; fine arts", "category": "noun"},
    {"simplified": "传统", "traditional": "傳統", "pinyin": "chuán tǒng", "english": "tradition; traditional", "category": "noun"},
    {"simplified": "风俗", "traditional": "風俗", "pinyin": "fēng sú", "english": "custom; convention", "category": "noun"},
    {"simplified": "教育", "traditional": "教育", "pinyin": "jiào yù", "english": "education; to educate", "category": "noun"},
    {"simplified": "专业", "traditional": "專業", "pinyin": "zhuān yè", "english": "major; specialty; professional", "category": "noun"},
    {"simplified": "学期", "traditional": "學期", "pinyin": "xué qī", "english": "semester; school term", "category": "noun"},
    {"simplified": "课程", "traditional": "課程", "pinyin": "kè chéng", "english": "course; curriculum", "category": "noun"},
    {"simplified": "成绩", "traditional": "成績", "pinyin": "chéng jì", "english": "score; achievement; result", "category": "noun"},
    {"simplified": "成语", "traditional": "成語", "pinyin": "chéng yǔ", "english": "idiom; set phrase", "category": "noun"},

    # --- Daily Life & Objects ---
    {"simplified": "零食", "traditional": "零食", "pinyin": "líng shí", "english": "snack; between-meal nibbles", "category": "noun"},
    {"simplified": "食品", "traditional": "食品", "pinyin": "shí pǐn", "english": "food; food products", "category": "noun"},
    {"simplified": "家具", "traditional": "傢具", "pinyin": "jiā jù", "english": "furniture", "category": "noun"},
    {"simplified": "钥匙", "traditional": "鑰匙", "pinyin": "yào shi", "english": "key", "category": "noun"},
    {"simplified": "镜子", "traditional": "鏡子", "pinyin": "jìng zi", "english": "mirror", "category": "noun"},
    {"simplified": "工具", "traditional": "工具", "pinyin": "gōng jù", "english": "tool; instrument", "category": "noun"},
    {"simplified": "日历", "traditional": "日曆", "pinyin": "rì lì", "english": "calendar", "category": "noun"},
    {"simplified": "日记", "traditional": "日記", "pinyin": "rì jì", "english": "diary; journal", "category": "noun"},
    {"simplified": "方式", "traditional": "方式", "pinyin": "fāng shì", "english": "way; method; manner", "category": "noun"},
    {"simplified": "方法", "traditional": "方法", "pinyin": "fāng fǎ", "english": "method; way; approach", "category": "noun"},
    {"simplified": "方面", "traditional": "方面", "pinyin": "fāng miàn", "english": "aspect; respect; side", "category": "noun"},
    {"simplified": "条件", "traditional": "條件", "pinyin": "tiáo jiàn", "english": "condition; requirement", "category": "noun"},
    {"simplified": "机会", "traditional": "機會", "pinyin": "jī huì", "english": "opportunity; chance", "category": "noun"},
    {"simplified": "过程", "traditional": "過程", "pinyin": "guò chéng", "english": "process; course", "category": "noun"},
    {"simplified": "结果", "traditional": "結果", "pinyin": "jié guǒ", "english": "result; outcome", "category": "noun"},
    {"simplified": "目标", "traditional": "目標", "pinyin": "mù biāo", "english": "goal; target; objective", "category": "noun"},
    {"simplified": "力量", "traditional": "力量", "pinyin": "lì liàng", "english": "power; strength; force", "category": "noun"},
    {"simplified": "能力", "traditional": "能力", "pinyin": "néng lì", "english": "ability; capability", "category": "noun"},
    {"simplified": "水平", "traditional": "水平", "pinyin": "shuǐ píng", "english": "level; standard; horizontal", "category": "noun"},

    # --- Health & Body ---
    {"simplified": "健康", "traditional": "健康", "pinyin": "jiàn kāng", "english": "health; healthy", "category": "noun"},
    {"simplified": "疾病", "traditional": "疾病", "pinyin": "jí bìng", "english": "disease; illness", "category": "noun"},
    {"simplified": "心理", "traditional": "心理", "pinyin": "xīn lǐ", "english": "psychology; mentality", "category": "noun"},
    {"simplified": "生命", "traditional": "生命", "pinyin": "shēng mìng", "english": "life; living", "category": "noun"},
    {"simplified": "皮肤", "traditional": "皮膚", "pinyin": "pí fū", "english": "skin", "category": "noun"},
    {"simplified": "肌肉", "traditional": "肌肉", "pinyin": "jī ròu", "english": "muscle", "category": "noun"},
    {"simplified": "血液", "traditional": "血液", "pinyin": "xuè yè", "english": "blood", "category": "noun"},

    # --- Places & Locations ---
    {"simplified": "地区", "traditional": "地區", "pinyin": "dì qū", "english": "region; area; district", "category": "noun"},
    {"simplified": "地球", "traditional": "地球", "pinyin": "dì qiú", "english": "earth; the globe", "category": "noun"},
    {"simplified": "大陆", "traditional": "大陸", "pinyin": "dà lù", "english": "continent; mainland", "category": "noun"},
    {"simplified": "首都", "traditional": "首都", "pinyin": "shǒu dū", "english": "capital city", "category": "noun"},
    {"simplified": "农村", "traditional": "農村", "pinyin": "nóng cūn", "english": "rural area; countryside", "category": "noun"},
    {"simplified": "城市", "traditional": "城市", "pinyin": "chéng shì", "english": "city; town", "category": "noun"},

    # --- Communication & Media ---
    {"simplified": "语言", "traditional": "語言", "pinyin": "yǔ yán", "english": "language", "category": "noun"},
    {"simplified": "报道", "traditional": "報道", "pinyin": "bào dào", "english": "news report; to report", "category": "noun"},
    {"simplified": "内容", "traditional": "內容", "pinyin": "nèi róng", "english": "content; substance", "category": "noun"},
    {"simplified": "话题", "traditional": "話題", "pinyin": "huà tí", "english": "topic; subject of conversation", "category": "noun"},
    {"simplified": "标准", "traditional": "標準", "pinyin": "biāo zhǔn", "english": "standard; criterion", "category": "noun"},
    {"simplified": "形式", "traditional": "形式", "pinyin": "xíng shì", "english": "form; format; formality", "category": "noun"},
    {"simplified": "形象", "traditional": "形象", "pinyin": "xíng xiàng", "english": "image; figure; vivid", "category": "noun"},
    {"simplified": "形状", "traditional": "形狀", "pinyin": "xíng zhuàng", "english": "shape; form; figure", "category": "noun"},

    # ============================================================
    # VERBS (~200 words)
    # ============================================================

    # --- Action & Behavior ---
    {"simplified": "承担", "traditional": "承擔", "pinyin": "chéng dān", "english": "to bear; to undertake; to assume", "category": "verb"},
    {"simplified": "承认", "traditional": "承認", "pinyin": "chéng rèn", "english": "to admit; to acknowledge; to recognize", "category": "verb"},
    {"simplified": "代替", "traditional": "代替", "pinyin": "dài tì", "english": "to replace; to substitute for", "category": "verb"},
    {"simplified": "对待", "traditional": "對待", "pinyin": "duì dài", "english": "to treat; to handle", "category": "verb"},
    {"simplified": "发挥", "traditional": "發揮", "pinyin": "fā huī", "english": "to bring into play; to give full scope to", "category": "verb"},
    {"simplified": "反对", "traditional": "反對", "pinyin": "fǎn duì", "english": "to oppose; to be against", "category": "verb"},
    {"simplified": "反映", "traditional": "反映", "pinyin": "fǎn yìng", "english": "to reflect; to mirror; to report", "category": "verb"},
    {"simplified": "改革", "traditional": "改革", "pinyin": "gǎi gé", "english": "to reform; reform", "category": "verb"},
    {"simplified": "赶紧", "traditional": "趕緊", "pinyin": "gǎn jǐn", "english": "to hurry; to hasten; quickly", "category": "verb"},
    {"simplified": "鼓励", "traditional": "鼓勵", "pinyin": "gǔ lì", "english": "to encourage; to inspire", "category": "verb"},
    {"simplified": "管理", "traditional": "管理", "pinyin": "guǎn lǐ", "english": "to manage; to administer; management", "category": "verb"},
    {"simplified": "合作", "traditional": "合作", "pinyin": "hé zuò", "english": "to cooperate; to collaborate", "category": "verb"},
    {"simplified": "忽视", "traditional": "忽視", "pinyin": "hū shì", "english": "to ignore; to neglect; to overlook", "category": "verb"},
    {"simplified": "获得", "traditional": "獲得", "pinyin": "huò dé", "english": "to obtain; to acquire; to gain", "category": "verb"},
    {"simplified": "集中", "traditional": "集中", "pinyin": "jí zhōng", "english": "to concentrate; to focus; to centralize", "category": "verb"},
    {"simplified": "坚持", "traditional": "堅持", "pinyin": "jiān chí", "english": "to persist in; to insist on", "category": "verb"},
    {"simplified": "建立", "traditional": "建立", "pinyin": "jiàn lì", "english": "to establish; to set up; to found", "category": "verb"},
    {"simplified": "交流", "traditional": "交流", "pinyin": "jiāo liú", "english": "to exchange; to communicate", "category": "verb"},
    {"simplified": "接触", "traditional": "接觸", "pinyin": "jiē chù", "english": "to contact; to get in touch with", "category": "verb"},
    {"simplified": "解释", "traditional": "解釋", "pinyin": "jiě shì", "english": "to explain; to interpret; explanation", "category": "verb"},
    {"simplified": "尽量", "traditional": "盡量", "pinyin": "jǐn liàng", "english": "to try one's best; as much as possible", "category": "verb"},
    {"simplified": "举办", "traditional": "舉辦", "pinyin": "jǔ bàn", "english": "to hold; to host (an event)", "category": "verb"},
    {"simplified": "拒绝", "traditional": "拒絕", "pinyin": "jù jué", "english": "to refuse; to reject; to decline", "category": "verb"},
    {"simplified": "控制", "traditional": "控制", "pinyin": "kòng zhì", "english": "to control; to dominate", "category": "verb"},
    {"simplified": "扩大", "traditional": "擴大", "pinyin": "kuò dà", "english": "to expand; to enlarge; to extend", "category": "verb"},
    {"simplified": "了解", "traditional": "了解", "pinyin": "liǎo jiě", "english": "to understand; to find out", "category": "verb"},
    {"simplified": "利用", "traditional": "利用", "pinyin": "lì yòng", "english": "to use; to utilize; to take advantage of", "category": "verb"},
    {"simplified": "面对", "traditional": "面對", "pinyin": "miàn duì", "english": "to face; to confront", "category": "verb"},
    {"simplified": "模仿", "traditional": "模仿", "pinyin": "mó fǎng", "english": "to imitate; to copy; to mimic", "category": "verb"},
    {"simplified": "判断", "traditional": "判斷", "pinyin": "pàn duàn", "english": "to judge; to determine; judgment", "category": "verb"},
    {"simplified": "培养", "traditional": "培養", "pinyin": "péi yǎng", "english": "to cultivate; to train; to foster", "category": "verb"},
    {"simplified": "评价", "traditional": "評價", "pinyin": "píng jià", "english": "to evaluate; to appraise; evaluation", "category": "verb"},
    {"simplified": "确定", "traditional": "確定", "pinyin": "què dìng", "english": "to determine; to confirm; definite", "category": "verb"},
    {"simplified": "确认", "traditional": "確認", "pinyin": "què rèn", "english": "to confirm; to verify", "category": "verb"},
    {"simplified": "认识", "traditional": "認識", "pinyin": "rèn shi", "english": "to know; to recognize; to be acquainted with", "category": "verb"},
    {"simplified": "实现", "traditional": "實現", "pinyin": "shí xiàn", "english": "to realize; to achieve; to accomplish", "category": "verb"},
    {"simplified": "实行", "traditional": "實行", "pinyin": "shí xíng", "english": "to implement; to carry out; to put into practice", "category": "verb"},
    {"simplified": "适合", "traditional": "適合", "pinyin": "shì hé", "english": "to suit; to fit; to be suitable", "category": "verb"},
    {"simplified": "说明", "traditional": "說明", "pinyin": "shuō míng", "english": "to explain; to illustrate; explanation", "category": "verb"},
    {"simplified": "讨论", "traditional": "討論", "pinyin": "tǎo lùn", "english": "to discuss; to debate; discussion", "category": "verb"},
    {"simplified": "提供", "traditional": "提供", "pinyin": "tí gōng", "english": "to provide; to supply; to offer", "category": "verb"},
    {"simplified": "同意", "traditional": "同意", "pinyin": "tóng yì", "english": "to agree; to consent; to approve", "category": "verb"},
    {"simplified": "投资", "traditional": "投資", "pinyin": "tóu zī", "english": "to invest; investment", "category": "verb"},
    {"simplified": "推广", "traditional": "推廣", "pinyin": "tuī guǎng", "english": "to promote; to popularize; to spread", "category": "verb"},
    {"simplified": "维护", "traditional": "維護", "pinyin": "wéi hù", "english": "to maintain; to defend; to safeguard", "category": "verb"},
    {"simplified": "委托", "traditional": "委託", "pinyin": "wěi tuō", "english": "to entrust; to commission", "category": "verb"},
    {"simplified": "吸引", "traditional": "吸引", "pinyin": "xī yǐn", "english": "to attract; to fascinate; to draw", "category": "verb"},
    {"simplified": "想象", "traditional": "想象", "pinyin": "xiǎng xiàng", "english": "to imagine; to fancy; imagination", "category": "verb"},
    {"simplified": "消费", "traditional": "消費", "pinyin": "xiāo fèi", "english": "to consume; consumption", "category": "verb"},
    {"simplified": "形成", "traditional": "形成", "pinyin": "xíng chéng", "english": "to form; to take shape", "category": "verb"},
    {"simplified": "修改", "traditional": "修改", "pinyin": "xiū gǎi", "english": "to revise; to modify; to amend", "category": "verb"},
    {"simplified": "选择", "traditional": "選擇", "pinyin": "xuǎn zé", "english": "to choose; to select; choice", "category": "verb"},
    {"simplified": "研究", "traditional": "研究", "pinyin": "yán jiū", "english": "to research; to study; research", "category": "verb"},
    {"simplified": "要求", "traditional": "要求", "pinyin": "yāo qiú", "english": "to require; to demand; requirement", "category": "verb"},
    {"simplified": "引起", "traditional": "引起", "pinyin": "yǐn qǐ", "english": "to cause; to give rise to; to arouse", "category": "verb"},
    {"simplified": "应用", "traditional": "應用", "pinyin": "yìng yòng", "english": "to apply; to use; application", "category": "verb"},
    {"simplified": "影响", "traditional": "影響", "pinyin": "yǐng xiǎng", "english": "to influence; to affect; influence", "category": "verb"},
    {"simplified": "拥有", "traditional": "擁有", "pinyin": "yōng yǒu", "english": "to possess; to own; to have", "category": "verb"},
    {"simplified": "预防", "traditional": "預防", "pinyin": "yù fáng", "english": "to prevent; to guard against", "category": "verb"},
    {"simplified": "允许", "traditional": "允許", "pinyin": "yǔn xǔ", "english": "to permit; to allow", "category": "verb"},
    {"simplified": "增加", "traditional": "增加", "pinyin": "zēng jiā", "english": "to increase; to add; to raise", "category": "verb"},
    {"simplified": "挣钱", "traditional": "掙錢", "pinyin": "zhèng qián", "english": "to earn money; to make money", "category": "verb"},
    {"simplified": "支持", "traditional": "支持", "pinyin": "zhī chí", "english": "to support; to back; to stand by", "category": "verb"},
    {"simplified": "组织", "traditional": "組織", "pinyin": "zǔ zhī", "english": "to organize; organization", "category": "verb"},
    {"simplified": "阻止", "traditional": "阻止", "pinyin": "zǔ zhǐ", "english": "to prevent; to stop; to block", "category": "verb"},

    # --- More Verbs ---
    {"simplified": "安排", "traditional": "安排", "pinyin": "ān pái", "english": "to arrange; to plan; arrangement", "category": "verb"},
    {"simplified": "保持", "traditional": "保持", "pinyin": "bǎo chí", "english": "to keep; to maintain; to preserve", "category": "verb"},
    {"simplified": "保护", "traditional": "保護", "pinyin": "bǎo hù", "english": "to protect; to safeguard", "category": "verb"},
    {"simplified": "保证", "traditional": "保證", "pinyin": "bǎo zhèng", "english": "to guarantee; to ensure; to promise", "category": "verb"},
    {"simplified": "表达", "traditional": "表達", "pinyin": "biǎo dá", "english": "to express; to convey", "category": "verb"},
    {"simplified": "表现", "traditional": "表現", "pinyin": "biǎo xiàn", "english": "to show; to display; performance", "category": "verb"},
    {"simplified": "表演", "traditional": "表演", "pinyin": "biǎo yǎn", "english": "to perform; performance", "category": "verb"},
    {"simplified": "表扬", "traditional": "表揚", "pinyin": "biǎo yáng", "english": "to praise; to commend", "category": "verb"},
    {"simplified": "猜", "traditional": "猜", "pinyin": "cāi", "english": "to guess; to speculate", "category": "verb"},
    {"simplified": "参观", "traditional": "參觀", "pinyin": "cān guān", "english": "to visit; to tour; to look around", "category": "verb"},
    {"simplified": "参与", "traditional": "參與", "pinyin": "cān yù", "english": "to participate in; to take part in", "category": "verb"},
    {"simplified": "采取", "traditional": "採取", "pinyin": "cǎi qǔ", "english": "to adopt; to take (measures)", "category": "verb"},
    {"simplified": "产生", "traditional": "產生", "pinyin": "chǎn shēng", "english": "to produce; to generate; to arise", "category": "verb"},
    {"simplified": "成立", "traditional": "成立", "pinyin": "chéng lì", "english": "to establish; to set up; to found", "category": "verb"},
    {"simplified": "充满", "traditional": "充滿", "pinyin": "chōng mǎn", "english": "to be full of; to be brimming with", "category": "verb"},
    {"simplified": "重复", "traditional": "重複", "pinyin": "chóng fù", "english": "to repeat; to duplicate", "category": "verb"},
    {"simplified": "处理", "traditional": "處理", "pinyin": "chǔ lǐ", "english": "to handle; to deal with; to process", "category": "verb"},
    {"simplified": "传播", "traditional": "傳播", "pinyin": "chuán bō", "english": "to spread; to disseminate; to broadcast", "category": "verb"},
    {"simplified": "创造", "traditional": "創造", "pinyin": "chuàng zào", "english": "to create; to produce; creation", "category": "verb"},
    {"simplified": "促进", "traditional": "促進", "pinyin": "cù jìn", "english": "to promote; to advance; to facilitate", "category": "verb"},
    {"simplified": "存在", "traditional": "存在", "pinyin": "cún zài", "english": "to exist; existence", "category": "verb"},
    {"simplified": "达到", "traditional": "達到", "pinyin": "dá dào", "english": "to reach; to achieve; to attain", "category": "verb"},
    {"simplified": "打工", "traditional": "打工", "pinyin": "dǎ gōng", "english": "to work (part-time or manual labor)", "category": "verb"},
    {"simplified": "打交道", "traditional": "打交道", "pinyin": "dǎ jiāo dào", "english": "to deal with; to have contact with", "category": "verb"},
    {"simplified": "导致", "traditional": "導致", "pinyin": "dǎo zhì", "english": "to lead to; to cause; to result in", "category": "verb"},
    {"simplified": "登记", "traditional": "登記", "pinyin": "dēng jì", "english": "to register; to sign up", "category": "verb"},
    {"simplified": "调查", "traditional": "調查", "pinyin": "diào chá", "english": "to investigate; to survey; investigation", "category": "verb"},
    {"simplified": "调整", "traditional": "調整", "pinyin": "tiáo zhěng", "english": "to adjust; to regulate; adjustment", "category": "verb"},
    {"simplified": "发展", "traditional": "發展", "pinyin": "fā zhǎn", "english": "to develop; development", "category": "verb"},
    {"simplified": "发明", "traditional": "發明", "pinyin": "fā míng", "english": "to invent; invention", "category": "verb"},
    {"simplified": "反复", "traditional": "反復", "pinyin": "fǎn fù", "english": "to repeat; repeatedly; again and again", "category": "verb"},
    {"simplified": "改善", "traditional": "改善", "pinyin": "gǎi shàn", "english": "to improve; to ameliorate", "category": "verb"},
    {"simplified": "感受", "traditional": "感受", "pinyin": "gǎn shòu", "english": "to feel; to experience; feeling", "category": "verb"},
    {"simplified": "感激", "traditional": "感激", "pinyin": "gǎn jī", "english": "to be grateful; to appreciate", "category": "verb"},
    {"simplified": "告别", "traditional": "告別", "pinyin": "gào bié", "english": "to bid farewell; to say goodbye", "category": "verb"},
    {"simplified": "公布", "traditional": "公佈", "pinyin": "gōng bù", "english": "to announce; to make public", "category": "verb"},
    {"simplified": "沟通", "traditional": "溝通", "pinyin": "gōu tōng", "english": "to communicate; communication", "category": "verb"},
    {"simplified": "估计", "traditional": "估計", "pinyin": "gū jì", "english": "to estimate; to reckon", "category": "verb"},
    {"simplified": "雇佣", "traditional": "雇傭", "pinyin": "gù yōng", "english": "to employ; to hire", "category": "verb"},
    {"simplified": "贡献", "traditional": "貢獻", "pinyin": "gòng xiàn", "english": "to contribute; contribution", "category": "verb"},
    {"simplified": "关闭", "traditional": "關閉", "pinyin": "guān bì", "english": "to close; to shut down", "category": "verb"},
    {"simplified": "观察", "traditional": "觀察", "pinyin": "guān chá", "english": "to observe; to watch; observation", "category": "verb"},
    {"simplified": "恢复", "traditional": "恢復", "pinyin": "huī fù", "english": "to recover; to restore; to resume", "category": "verb"},
    {"simplified": "回忆", "traditional": "回憶", "pinyin": "huí yì", "english": "to recall; to recollect; memory", "category": "verb"},
    {"simplified": "积累", "traditional": "積累", "pinyin": "jī lěi", "english": "to accumulate; to build up", "category": "verb"},
    {"simplified": "计划", "traditional": "計劃", "pinyin": "jì huà", "english": "to plan; plan; project", "category": "verb"},
    {"simplified": "记录", "traditional": "記錄", "pinyin": "jì lù", "english": "to record; record; note", "category": "verb"},
    {"simplified": "降低", "traditional": "降低", "pinyin": "jiàng dī", "english": "to reduce; to lower; to decrease", "category": "verb"},
    {"simplified": "交往", "traditional": "交往", "pinyin": "jiāo wǎng", "english": "to associate with; to interact", "category": "verb"},
    {"simplified": "接受", "traditional": "接受", "pinyin": "jiē shòu", "english": "to accept; to receive", "category": "verb"},
    {"simplified": "节约", "traditional": "節約", "pinyin": "jié yuē", "english": "to save; to economize; to conserve", "category": "verb"},
    {"simplified": "禁止", "traditional": "禁止", "pinyin": "jìn zhǐ", "english": "to prohibit; to forbid; to ban", "category": "verb"},
    {"simplified": "竞争", "traditional": "競爭", "pinyin": "jìng zhēng", "english": "to compete; competition", "category": "verb"},
    {"simplified": "考虑", "traditional": "考慮", "pinyin": "kǎo lǜ", "english": "to consider; to think about", "category": "verb"},
    {"simplified": "克服", "traditional": "克服", "pinyin": "kè fú", "english": "to overcome; to conquer", "category": "verb"},
    {"simplified": "理解", "traditional": "理解", "pinyin": "lǐ jiě", "english": "to understand; to comprehend", "category": "verb"},
    {"simplified": "联合", "traditional": "聯合", "pinyin": "lián hé", "english": "to unite; to combine; joint", "category": "verb"},
    {"simplified": "留学", "traditional": "留學", "pinyin": "liú xué", "english": "to study abroad", "category": "verb"},
    {"simplified": "满足", "traditional": "滿足", "pinyin": "mǎn zú", "english": "to satisfy; to meet (needs); satisfied", "category": "verb"},
    {"simplified": "描写", "traditional": "描寫", "pinyin": "miáo xiě", "english": "to describe; to depict; to portray", "category": "verb"},
    {"simplified": "目前", "traditional": "目前", "pinyin": "mù qián", "english": "at present; currently", "category": "verb"},
    {"simplified": "批评", "traditional": "批評", "pinyin": "pī píng", "english": "to criticize; criticism", "category": "verb"},
    {"simplified": "破坏", "traditional": "破壞", "pinyin": "pò huài", "english": "to destroy; to damage; to sabotage", "category": "verb"},
    {"simplified": "期待", "traditional": "期待", "pinyin": "qī dài", "english": "to look forward to; to expect", "category": "verb"},
    {"simplified": "取消", "traditional": "取消", "pinyin": "qǔ xiāo", "english": "to cancel; to abolish", "category": "verb"},
    {"simplified": "缺少", "traditional": "缺少", "pinyin": "quē shǎo", "english": "to lack; to be short of", "category": "verb"},
    {"simplified": "设计", "traditional": "設計", "pinyin": "shè jì", "english": "to design; design; plan", "category": "verb"},
    {"simplified": "申请", "traditional": "申請", "pinyin": "shēn qǐng", "english": "to apply for; application", "category": "verb"},
    {"simplified": "生产", "traditional": "生產", "pinyin": "shēng chǎn", "english": "to produce; to manufacture; production", "category": "verb"},
    {"simplified": "失败", "traditional": "失敗", "pinyin": "shī bài", "english": "to fail; failure; defeat", "category": "verb"},
    {"simplified": "实践", "traditional": "實踐", "pinyin": "shí jiàn", "english": "to practice; to put into practice", "category": "verb"},
    {"simplified": "使用", "traditional": "使用", "pinyin": "shǐ yòng", "english": "to use; to employ; to apply", "category": "verb"},
    {"simplified": "属于", "traditional": "屬於", "pinyin": "shǔ yú", "english": "to belong to; to be part of", "category": "verb"},
    {"simplified": "思考", "traditional": "思考", "pinyin": "sī kǎo", "english": "to think; to ponder; to reflect", "category": "verb"},
    {"simplified": "提高", "traditional": "提高", "pinyin": "tí gāo", "english": "to raise; to improve; to enhance", "category": "verb"},
    {"simplified": "提醒", "traditional": "提醒", "pinyin": "tí xǐng", "english": "to remind; to alert", "category": "verb"},
    {"simplified": "体现", "traditional": "體現", "pinyin": "tǐ xiàn", "english": "to embody; to reflect; to manifest", "category": "verb"},
    {"simplified": "体验", "traditional": "體驗", "pinyin": "tǐ yàn", "english": "to experience; to learn through experience", "category": "verb"},
    {"simplified": "通过", "traditional": "通過", "pinyin": "tōng guò", "english": "to pass through; by means of; via", "category": "verb"},
    {"simplified": "推迟", "traditional": "推遲", "pinyin": "tuī chí", "english": "to postpone; to delay; to put off", "category": "verb"},
    {"simplified": "完善", "traditional": "完善", "pinyin": "wán shàn", "english": "to perfect; to improve; perfect", "category": "verb"},
    {"simplified": "限制", "traditional": "限制", "pinyin": "xiàn zhì", "english": "to limit; to restrict; restriction", "category": "verb"},
    {"simplified": "相处", "traditional": "相處", "pinyin": "xiāng chǔ", "english": "to get along with; to interact", "category": "verb"},
    {"simplified": "享受", "traditional": "享受", "pinyin": "xiǎng shòu", "english": "to enjoy; enjoyment", "category": "verb"},
    {"simplified": "宣传", "traditional": "宣傳", "pinyin": "xuān chuán", "english": "to publicize; to propagate; publicity", "category": "verb"},
    {"simplified": "寻找", "traditional": "尋找", "pinyin": "xún zhǎo", "english": "to seek; to look for; to search", "category": "verb"},
    {"simplified": "遗憾", "traditional": "遺憾", "pinyin": "yí hàn", "english": "to regret; regret; pity", "category": "verb"},
    {"simplified": "证明", "traditional": "證明", "pinyin": "zhèng míng", "english": "to prove; to demonstrate; proof", "category": "verb"},
    {"simplified": "执行", "traditional": "執行", "pinyin": "zhí xíng", "english": "to carry out; to execute; to implement", "category": "verb"},
    {"simplified": "指导", "traditional": "指導", "pinyin": "zhǐ dǎo", "english": "to guide; to direct; guidance", "category": "verb"},
    {"simplified": "重视", "traditional": "重視", "pinyin": "zhòng shì", "english": "to attach importance to; to value", "category": "verb"},
    {"simplified": "转变", "traditional": "轉變", "pinyin": "zhuǎn biàn", "english": "to change; to transform; transformation", "category": "verb"},
    {"simplified": "追求", "traditional": "追求", "pinyin": "zhuī qiú", "english": "to pursue; to seek; pursuit", "category": "verb"},
    {"simplified": "总结", "traditional": "總結", "pinyin": "zǒng jié", "english": "to summarize; summary; conclusion", "category": "verb"},
    {"simplified": "尊重", "traditional": "尊重", "pinyin": "zūn zhòng", "english": "to respect; to esteem; respect", "category": "verb"},
    {"simplified": "遵守", "traditional": "遵守", "pinyin": "zūn shǒu", "english": "to observe; to abide by; to comply with", "category": "verb"},

    # ============================================================
    # ADJECTIVES (~100 words)
    # ============================================================
    {"simplified": "安静", "traditional": "安靜", "pinyin": "ān jìng", "english": "quiet; peaceful; calm", "category": "adjective"},
    {"simplified": "暗", "traditional": "暗", "pinyin": "àn", "english": "dark; dim; hidden", "category": "adjective"},
    {"simplified": "抱歉", "traditional": "抱歉", "pinyin": "bào qiàn", "english": "sorry; apologetic", "category": "adjective"},
    {"simplified": "悲观", "traditional": "悲觀", "pinyin": "bēi guān", "english": "pessimistic", "category": "adjective"},
    {"simplified": "必要", "traditional": "必要", "pinyin": "bì yào", "english": "necessary; essential", "category": "adjective"},
    {"simplified": "残酷", "traditional": "殘酷", "pinyin": "cán kù", "english": "cruel; brutal; ruthless", "category": "adjective"},
    {"simplified": "诚恳", "traditional": "誠懇", "pinyin": "chéng kěn", "english": "sincere; earnest; honest", "category": "adjective"},
    {"simplified": "充分", "traditional": "充分", "pinyin": "chōng fèn", "english": "ample; sufficient; full", "category": "adjective"},
    {"simplified": "出色", "traditional": "出色", "pinyin": "chū sè", "english": "outstanding; remarkable; splendid", "category": "adjective"},
    {"simplified": "粗心", "traditional": "粗心", "pinyin": "cū xīn", "english": "careless; thoughtless", "category": "adjective"},
    {"simplified": "独立", "traditional": "獨立", "pinyin": "dú lì", "english": "independent; to stand alone", "category": "adjective"},
    {"simplified": "烦恼", "traditional": "煩惱", "pinyin": "fán nǎo", "english": "worried; troubled; vexed", "category": "adjective"},
    {"simplified": "丰富", "traditional": "豐富", "pinyin": "fēng fù", "english": "rich; abundant; plentiful", "category": "adjective"},
    {"simplified": "复杂", "traditional": "複雜", "pinyin": "fù zá", "english": "complicated; complex", "category": "adjective"},
    {"simplified": "干燥", "traditional": "乾燥", "pinyin": "gān zào", "english": "dry; arid", "category": "adjective"},
    {"simplified": "高级", "traditional": "高級", "pinyin": "gāo jí", "english": "high-level; advanced; senior", "category": "adjective"},
    {"simplified": "公平", "traditional": "公平", "pinyin": "gōng píng", "english": "fair; just; impartial", "category": "adjective"},
    {"simplified": "光滑", "traditional": "光滑", "pinyin": "guāng huá", "english": "smooth; glossy; sleek", "category": "adjective"},
    {"simplified": "合理", "traditional": "合理", "pinyin": "hé lǐ", "english": "reasonable; rational; fair", "category": "adjective"},
    {"simplified": "活泼", "traditional": "活潑", "pinyin": "huó po", "english": "lively; vivacious; active", "category": "adjective"},
    {"simplified": "积极", "traditional": "積極", "pinyin": "jī jí", "english": "positive; active; enthusiastic", "category": "adjective"},
    {"simplified": "及时", "traditional": "及時", "pinyin": "jí shí", "english": "timely; prompt; in time", "category": "adjective"},
    {"simplified": "急", "traditional": "急", "pinyin": "jí", "english": "urgent; anxious; hurried", "category": "adjective"},
    {"simplified": "寂寞", "traditional": "寂寞", "pinyin": "jì mò", "english": "lonely; lonesome; solitary", "category": "adjective"},
    {"simplified": "坚强", "traditional": "堅強", "pinyin": "jiān qiáng", "english": "strong; firm; staunch", "category": "adjective"},
    {"simplified": "简单", "traditional": "簡單", "pinyin": "jiǎn dān", "english": "simple; easy; uncomplicated", "category": "adjective"},
    {"simplified": "谨慎", "traditional": "謹慎", "pinyin": "jǐn shèn", "english": "cautious; careful; prudent", "category": "adjective"},
    {"simplified": "具体", "traditional": "具體", "pinyin": "jù tǐ", "english": "concrete; specific; detailed", "category": "adjective"},
    {"simplified": "可靠", "traditional": "可靠", "pinyin": "kě kào", "english": "reliable; dependable; trustworthy", "category": "adjective"},
    {"simplified": "客观", "traditional": "客觀", "pinyin": "kè guān", "english": "objective; impartial", "category": "adjective"},
    {"simplified": "冷静", "traditional": "冷靜", "pinyin": "lěng jìng", "english": "calm; cool-headed; composed", "category": "adjective"},
    {"simplified": "厉害", "traditional": "厲害", "pinyin": "lì hai", "english": "fierce; formidable; impressive", "category": "adjective"},
    {"simplified": "灵活", "traditional": "靈活", "pinyin": "líng huó", "english": "flexible; agile; nimble", "category": "adjective"},
    {"simplified": "明显", "traditional": "明顯", "pinyin": "míng xiǎn", "english": "obvious; evident; clear", "category": "adjective"},
    {"simplified": "模糊", "traditional": "模糊", "pinyin": "mó hu", "english": "vague; blurred; fuzzy", "category": "adjective"},
    {"simplified": "耐心", "traditional": "耐心", "pinyin": "nài xīn", "english": "patient; patience", "category": "adjective"},
    {"simplified": "能干", "traditional": "能幹", "pinyin": "néng gàn", "english": "capable; competent; able", "category": "adjective"},
    {"simplified": "平等", "traditional": "平等", "pinyin": "píng děng", "english": "equal; equality", "category": "adjective"},
    {"simplified": "谦虚", "traditional": "謙虛", "pinyin": "qiān xū", "english": "modest; humble", "category": "adjective"},
    {"simplified": "强烈", "traditional": "強烈", "pinyin": "qiáng liè", "english": "strong; intense; violent", "category": "adjective"},
    {"simplified": "勤劳", "traditional": "勤勞", "pinyin": "qín láo", "english": "hardworking; industrious; diligent", "category": "adjective"},
    {"simplified": "热情", "traditional": "熱情", "pinyin": "rè qíng", "english": "enthusiastic; warm; passionate", "category": "adjective"},
    {"simplified": "认真", "traditional": "認真", "pinyin": "rèn zhēn", "english": "serious; earnest; conscientious", "category": "adjective"},
    {"simplified": "善良", "traditional": "善良", "pinyin": "shàn liáng", "english": "kind-hearted; good-natured; kind", "category": "adjective"},
    {"simplified": "深刻", "traditional": "深刻", "pinyin": "shēn kè", "english": "profound; deep; penetrating", "category": "adjective"},
    {"simplified": "实际", "traditional": "實際", "pinyin": "shí jì", "english": "practical; realistic; actual", "category": "adjective"},
    {"simplified": "熟悉", "traditional": "熟悉", "pinyin": "shú xī", "english": "familiar; well-acquainted with", "category": "adjective"},
    {"simplified": "随便", "traditional": "隨便", "pinyin": "suí biàn", "english": "casual; careless; whatever", "category": "adjective"},
    {"simplified": "温暖", "traditional": "溫暖", "pinyin": "wēn nuǎn", "english": "warm; nice and warm", "category": "adjective"},
    {"simplified": "稳定", "traditional": "穩定", "pinyin": "wěn dìng", "english": "stable; steady; to stabilize", "category": "adjective"},
    {"simplified": "无聊", "traditional": "無聊", "pinyin": "wú liáo", "english": "bored; boring; dull", "category": "adjective"},
    {"simplified": "详细", "traditional": "詳細", "pinyin": "xiáng xì", "english": "detailed; thorough; in detail", "category": "adjective"},
    {"simplified": "严格", "traditional": "嚴格", "pinyin": "yán gé", "english": "strict; rigorous; stringent", "category": "adjective"},
    {"simplified": "严重", "traditional": "嚴重", "pinyin": "yán zhòng", "english": "serious; severe; grave", "category": "adjective"},
    {"simplified": "勇敢", "traditional": "勇敢", "pinyin": "yǒng gǎn", "english": "brave; courageous; valiant", "category": "adjective"},
    {"simplified": "优秀", "traditional": "優秀", "pinyin": "yōu xiù", "english": "outstanding; excellent; splendid", "category": "adjective"},
    {"simplified": "有趣", "traditional": "有趣", "pinyin": "yǒu qù", "english": "interesting; amusing; fun", "category": "adjective"},
    {"simplified": "真实", "traditional": "真實", "pinyin": "zhēn shí", "english": "real; true; authentic", "category": "adjective"},
    {"simplified": "正式", "traditional": "正式", "pinyin": "zhèng shì", "english": "formal; official", "category": "adjective"},
    {"simplified": "主动", "traditional": "主動", "pinyin": "zhǔ dòng", "english": "active; initiative; proactive", "category": "adjective"},
    {"simplified": "自信", "traditional": "自信", "pinyin": "zì xìn", "english": "confident; self-confident", "category": "adjective"},
    {"simplified": "自由", "traditional": "自由", "pinyin": "zì yóu", "english": "free; freedom; liberty", "category": "adjective"},
    {"simplified": "安全", "traditional": "安全", "pinyin": "ān quán", "english": "safe; secure; safety", "category": "adjective"},
    {"simplified": "宝贵", "traditional": "寶貴", "pinyin": "bǎo guì", "english": "valuable; precious", "category": "adjective"},
    {"simplified": "彻底", "traditional": "徹底", "pinyin": "chè dǐ", "english": "thorough; complete; utter", "category": "adjective"},
    {"simplified": "成熟", "traditional": "成熟", "pinyin": "chéng shú", "english": "mature; ripe", "category": "adjective"},
    {"simplified": "诚实", "traditional": "誠實", "pinyin": "chéng shí", "english": "honest; truthful; sincere", "category": "adjective"},
    {"simplified": "抽象", "traditional": "抽象", "pinyin": "chōu xiàng", "english": "abstract", "category": "adjective"},
    {"simplified": "传统", "traditional": "傳統", "pinyin": "chuán tǒng", "english": "traditional; tradition", "category": "adjective"},
    {"simplified": "大方", "traditional": "大方", "pinyin": "dà fang", "english": "generous; natural and poised", "category": "adjective"},
    {"simplified": "单调", "traditional": "單調", "pinyin": "dān diào", "english": "monotonous; dull; boring", "category": "adjective"},
    {"simplified": "固定", "traditional": "固定", "pinyin": "gù dìng", "english": "fixed; regular; to fix", "category": "adjective"},
    {"simplified": "豪华", "traditional": "豪華", "pinyin": "háo huá", "english": "luxurious; extravagant; splendid", "category": "adjective"},
    {"simplified": "紧急", "traditional": "緊急", "pinyin": "jǐn jí", "english": "urgent; emergency; pressing", "category": "adjective"},
    {"simplified": "精彩", "traditional": "精彩", "pinyin": "jīng cǎi", "english": "brilliant; wonderful; splendid", "category": "adjective"},
    {"simplified": "乐观", "traditional": "樂觀", "pinyin": "lè guān", "english": "optimistic; hopeful", "category": "adjective"},
    {"simplified": "良好", "traditional": "良好", "pinyin": "liáng hǎo", "english": "good; fine; favorable", "category": "adjective"},
    {"simplified": "美丽", "traditional": "美麗", "pinyin": "měi lì", "english": "beautiful; gorgeous", "category": "adjective"},
    {"simplified": "明确", "traditional": "明確", "pinyin": "míng què", "english": "clear; definite; explicit", "category": "adjective"},
    {"simplified": "普遍", "traditional": "普遍", "pinyin": "pǔ biàn", "english": "universal; general; widespread", "category": "adjective"},
    {"simplified": "朴素", "traditional": "樸素", "pinyin": "pǔ sù", "english": "plain; simple; austere", "category": "adjective"},
    {"simplified": "齐全", "traditional": "齊全", "pinyin": "qí quán", "english": "complete; all available", "category": "adjective"},
    {"simplified": "巧妙", "traditional": "巧妙", "pinyin": "qiǎo miào", "english": "clever; ingenious; skillful", "category": "adjective"},
    {"simplified": "勤奋", "traditional": "勤奮", "pinyin": "qín fèn", "english": "diligent; hardworking; studious", "category": "adjective"},
    {"simplified": "清楚", "traditional": "清楚", "pinyin": "qīng chu", "english": "clear; distinct; obvious", "category": "adjective"},
    {"simplified": "全面", "traditional": "全面", "pinyin": "quán miàn", "english": "comprehensive; overall; all-round", "category": "adjective"},
    {"simplified": "柔和", "traditional": "柔和", "pinyin": "róu hé", "english": "gentle; soft; mild", "category": "adjective"},
    {"simplified": "温柔", "traditional": "溫柔", "pinyin": "wēn róu", "english": "gentle; tender; soft", "category": "adjective"},
    {"simplified": "先进", "traditional": "先進", "pinyin": "xiān jìn", "english": "advanced; progressive", "category": "adjective"},
    {"simplified": "现代", "traditional": "現代", "pinyin": "xiàn dài", "english": "modern; contemporary", "category": "adjective"},
    {"simplified": "有效", "traditional": "有效", "pinyin": "yǒu xiào", "english": "effective; valid", "category": "adjective"},
    {"simplified": "愉快", "traditional": "愉快", "pinyin": "yú kuài", "english": "happy; cheerful; pleasant", "category": "adjective"},
    {"simplified": "重要", "traditional": "重要", "pinyin": "zhòng yào", "english": "important; significant; major", "category": "adjective"},
    {"simplified": "主要", "traditional": "主要", "pinyin": "zhǔ yào", "english": "main; principal; major", "category": "adjective"},

    # ============================================================
    # ADVERBS (~60 words)
    # ============================================================
    {"simplified": "按照", "traditional": "按照", "pinyin": "àn zhào", "english": "according to; in accordance with", "category": "adverb"},
    {"simplified": "不断", "traditional": "不斷", "pinyin": "bù duàn", "english": "continuously; unceasingly; constantly", "category": "adverb"},
    {"simplified": "不管", "traditional": "不管", "pinyin": "bù guǎn", "english": "no matter; regardless of", "category": "adverb"},
    {"simplified": "不然", "traditional": "不然", "pinyin": "bù rán", "english": "otherwise; or else; if not", "category": "adverb"},
    {"simplified": "不仅", "traditional": "不僅", "pinyin": "bù jǐn", "english": "not only; not merely", "category": "adverb"},
    {"simplified": "曾经", "traditional": "曾經", "pinyin": "céng jīng", "english": "once; formerly; ever", "category": "adverb"},
    {"simplified": "趁", "traditional": "趁", "pinyin": "chèn", "english": "to take advantage of (a situation)", "category": "adverb"},
    {"simplified": "从此", "traditional": "從此", "pinyin": "cóng cǐ", "english": "from now on; henceforth", "category": "adverb"},
    {"simplified": "到底", "traditional": "到底", "pinyin": "dào dǐ", "english": "after all; in the end; exactly", "category": "adverb"},
    {"simplified": "反正", "traditional": "反正", "pinyin": "fǎn zhèng", "english": "anyway; in any case; anyhow", "category": "adverb"},
    {"simplified": "纷纷", "traditional": "紛紛", "pinyin": "fēn fēn", "english": "one after another; in succession", "category": "adverb"},
    {"simplified": "否则", "traditional": "否則", "pinyin": "fǒu zé", "english": "otherwise; or else; if not", "category": "adverb"},
    {"simplified": "刚才", "traditional": "剛才", "pinyin": "gāng cái", "english": "just now; a moment ago", "category": "adverb"},
    {"simplified": "果然", "traditional": "果然", "pinyin": "guǒ rán", "english": "as expected; sure enough; indeed", "category": "adverb"},
    {"simplified": "何必", "traditional": "何必", "pinyin": "hé bì", "english": "why bother; there is no need", "category": "adverb"},
    {"simplified": "即使", "traditional": "即使", "pinyin": "jí shǐ", "english": "even if; even though", "category": "adverb"},
    {"simplified": "尽管", "traditional": "儘管", "pinyin": "jǐn guǎn", "english": "despite; although; even though", "category": "adverb"},
    {"simplified": "竟然", "traditional": "竟然", "pinyin": "jìng rán", "english": "unexpectedly; to one's surprise", "category": "adverb"},
    {"simplified": "连忙", "traditional": "連忙", "pinyin": "lián máng", "english": "hurriedly; promptly; at once", "category": "adverb"},
    {"simplified": "另外", "traditional": "另外", "pinyin": "lìng wài", "english": "in addition; moreover; besides", "category": "adverb"},
    {"simplified": "难怪", "traditional": "難怪", "pinyin": "nán guài", "english": "no wonder; not surprising", "category": "adverb"},
    {"simplified": "难道", "traditional": "難道", "pinyin": "nán dào", "english": "could it be that; don't tell me", "category": "adverb"},
    {"simplified": "偶尔", "traditional": "偶爾", "pinyin": "ǒu ěr", "english": "occasionally; once in a while", "category": "adverb"},
    {"simplified": "其实", "traditional": "其實", "pinyin": "qí shí", "english": "actually; in fact; as a matter of fact", "category": "adverb"},
    {"simplified": "恰好", "traditional": "恰好", "pinyin": "qià hǎo", "english": "just right; exactly; as it happens", "category": "adverb"},
    {"simplified": "仍然", "traditional": "仍然", "pinyin": "réng rán", "english": "still; yet; as before", "category": "adverb"},
    {"simplified": "似乎", "traditional": "似乎", "pinyin": "sì hū", "english": "seemingly; as if; it seems", "category": "adverb"},
    {"simplified": "随时", "traditional": "隨時", "pinyin": "suí shí", "english": "at any time; at all times", "category": "adverb"},
    {"simplified": "特意", "traditional": "特意", "pinyin": "tè yì", "english": "specially; deliberately; on purpose", "category": "adverb"},
    {"simplified": "万一", "traditional": "萬一", "pinyin": "wàn yī", "english": "just in case; if by any chance", "category": "adverb"},
    {"simplified": "往往", "traditional": "往往", "pinyin": "wǎng wǎng", "english": "often; frequently; usually", "category": "adverb"},
    {"simplified": "未必", "traditional": "未必", "pinyin": "wèi bì", "english": "not necessarily; may not", "category": "adverb"},
    {"simplified": "无论", "traditional": "無論", "pinyin": "wú lùn", "english": "no matter what; regardless", "category": "adverb"},
    {"simplified": "显然", "traditional": "顯然", "pinyin": "xiǎn rán", "english": "obviously; evidently; clearly", "category": "adverb"},
    {"simplified": "幸亏", "traditional": "幸虧", "pinyin": "xìng kuī", "english": "fortunately; luckily", "category": "adverb"},
    {"simplified": "也许", "traditional": "也許", "pinyin": "yě xǔ", "english": "perhaps; maybe; possibly", "category": "adverb"},
    {"simplified": "依然", "traditional": "依然", "pinyin": "yī rán", "english": "still; as before", "category": "adverb"},
    {"simplified": "一旦", "traditional": "一旦", "pinyin": "yí dàn", "english": "once; in case; in the event of", "category": "adverb"},
    {"simplified": "由于", "traditional": "由於", "pinyin": "yóu yú", "english": "due to; owing to; because of", "category": "adverb"},
    {"simplified": "逐渐", "traditional": "逐漸", "pinyin": "zhú jiàn", "english": "gradually; little by little; step by step", "category": "adverb"},
    {"simplified": "总算", "traditional": "總算", "pinyin": "zǒng suàn", "english": "finally; at last; in the end", "category": "adverb"},
    {"simplified": "毕竟", "traditional": "畢竟", "pinyin": "bì jìng", "english": "after all; when all is said and done", "category": "adverb"},
    {"simplified": "不得不", "traditional": "不得不", "pinyin": "bù dé bù", "english": "have to; cannot but; have no choice", "category": "adverb"},
    {"simplified": "不见得", "traditional": "不見得", "pinyin": "bù jiàn de", "english": "not necessarily; not likely", "category": "adverb"},
    {"simplified": "从来", "traditional": "從來", "pinyin": "cóng lái", "english": "always; at all times; never (with neg.)", "category": "adverb"},
    {"simplified": "大约", "traditional": "大約", "pinyin": "dà yuē", "english": "approximately; about; roughly", "category": "adverb"},
    {"simplified": "当然", "traditional": "當然", "pinyin": "dāng rán", "english": "of course; naturally; certainly", "category": "adverb"},
    {"simplified": "的确", "traditional": "的確", "pinyin": "dí què", "english": "indeed; really; truly", "category": "adverb"},
    {"simplified": "分别", "traditional": "分別", "pinyin": "fēn bié", "english": "respectively; separately; to part", "category": "adverb"},
    {"simplified": "根本", "traditional": "根本", "pinyin": "gēn běn", "english": "fundamental; at all; simply", "category": "adverb"},
    {"simplified": "恐怕", "traditional": "恐怕", "pinyin": "kǒng pà", "english": "I'm afraid; perhaps; probably", "category": "adverb"},
    {"simplified": "立刻", "traditional": "立刻", "pinyin": "lì kè", "english": "immediately; at once; right away", "category": "adverb"},
    {"simplified": "千万", "traditional": "千萬", "pinyin": "qiān wàn", "english": "by all means; absolutely must", "category": "adverb"},
    {"simplified": "确实", "traditional": "確實", "pinyin": "què shí", "english": "indeed; really; truly; certainly", "category": "adverb"},
    {"simplified": "始终", "traditional": "始終", "pinyin": "shǐ zhōng", "english": "from beginning to end; all along", "category": "adverb"},
    {"simplified": "实在", "traditional": "實在", "pinyin": "shí zài", "english": "really; truly; honestly", "category": "adverb"},
    {"simplified": "特别", "traditional": "特別", "pinyin": "tè bié", "english": "especially; particularly; special", "category": "adverb"},
    {"simplified": "通常", "traditional": "通常", "pinyin": "tōng cháng", "english": "usually; normally; generally", "category": "adverb"},
    {"simplified": "相当", "traditional": "相當", "pinyin": "xiāng dāng", "english": "quite; fairly; considerably", "category": "adverb"},

    # ============================================================
    # CONJUNCTIONS (~20 words)
    # ============================================================
    {"simplified": "并且", "traditional": "並且", "pinyin": "bìng qiě", "english": "and; besides; moreover", "category": "conjunction"},
    {"simplified": "不过", "traditional": "不過", "pinyin": "bú guò", "english": "however; but; only", "category": "conjunction"},
    {"simplified": "除非", "traditional": "除非", "pinyin": "chú fēi", "english": "unless; only if", "category": "conjunction"},
    {"simplified": "而且", "traditional": "而且", "pinyin": "ér qiě", "english": "moreover; and also; furthermore", "category": "conjunction"},
    {"simplified": "何况", "traditional": "何況", "pinyin": "hé kuàng", "english": "let alone; much less; all the more", "category": "conjunction"},
    {"simplified": "既然", "traditional": "既然", "pinyin": "jì rán", "english": "since; now that; given that", "category": "conjunction"},
    {"simplified": "尽管", "traditional": "儘管", "pinyin": "jǐn guǎn", "english": "although; even though; despite", "category": "conjunction"},
    {"simplified": "可见", "traditional": "可見", "pinyin": "kě jiàn", "english": "it can be seen that; it is clear", "category": "conjunction"},
    {"simplified": "宁可", "traditional": "寧可", "pinyin": "nìng kě", "english": "would rather; preferably", "category": "conjunction"},
    {"simplified": "然而", "traditional": "然而", "pinyin": "rán ér", "english": "however; but; yet", "category": "conjunction"},
    {"simplified": "于是", "traditional": "於是", "pinyin": "yú shì", "english": "thereupon; as a result; so", "category": "conjunction"},
    {"simplified": "只要", "traditional": "只要", "pinyin": "zhǐ yào", "english": "as long as; provided that", "category": "conjunction"},
    {"simplified": "至于", "traditional": "至於", "pinyin": "zhì yú", "english": "as for; as to; regarding", "category": "conjunction"},
    {"simplified": "总之", "traditional": "總之", "pinyin": "zǒng zhī", "english": "in short; in a word; in brief", "category": "conjunction"},
    {"simplified": "从而", "traditional": "從而", "pinyin": "cóng ér", "english": "thereby; thus; and so", "category": "conjunction"},

    # ============================================================
    # PREPOSITIONS (~10 words)
    # ============================================================
    {"simplified": "根据", "traditional": "根據", "pinyin": "gēn jù", "english": "according to; based on; basis", "category": "preposition"},
    {"simplified": "关于", "traditional": "關於", "pinyin": "guān yú", "english": "about; regarding; concerning", "category": "preposition"},
    {"simplified": "对于", "traditional": "對於", "pinyin": "duì yú", "english": "with regard to; as for; towards", "category": "preposition"},
    {"simplified": "随着", "traditional": "隨著", "pinyin": "suí zhe", "english": "along with; as; following", "category": "preposition"},
    {"simplified": "通过", "traditional": "通過", "pinyin": "tōng guò", "english": "through; by means of; via", "category": "preposition"},
    {"simplified": "为了", "traditional": "為了", "pinyin": "wèi le", "english": "in order to; for the purpose of", "category": "preposition"},
    {"simplified": "沿", "traditional": "沿", "pinyin": "yán", "english": "along; following (a path)", "category": "preposition"},
    {"simplified": "以", "traditional": "以", "pinyin": "yǐ", "english": "by means of; with; in order to", "category": "preposition"},

    # ============================================================
    # MEASURE WORDS (~15 words)
    # ============================================================
    {"simplified": "倍", "traditional": "倍", "pinyin": "bèi", "english": "times; -fold (multiplier)", "category": "measure word"},
    {"simplified": "册", "traditional": "冊", "pinyin": "cè", "english": "volume; copy (of a book)", "category": "measure word"},
    {"simplified": "滴", "traditional": "滴", "pinyin": "dī", "english": "drop (of liquid)", "category": "measure word"},
    {"simplified": "顿", "traditional": "頓", "pinyin": "dùn", "english": "measure word for meals", "category": "measure word"},
    {"simplified": "届", "traditional": "屆", "pinyin": "jiè", "english": "session; period; class (of graduates)", "category": "measure word"},
    {"simplified": "棵", "traditional": "棵", "pinyin": "kē", "english": "measure word for trees/plants", "category": "measure word"},
    {"simplified": "粒", "traditional": "粒", "pinyin": "lì", "english": "grain; granule; measure word for small things", "category": "measure word"},
    {"simplified": "轮", "traditional": "輪", "pinyin": "lún", "english": "round; turn; wheel", "category": "measure word"},
    {"simplified": "篇", "traditional": "篇", "pinyin": "piān", "english": "measure word for articles/papers", "category": "measure word"},
    {"simplified": "片", "traditional": "片", "pinyin": "piàn", "english": "slice; piece; measure word for flat things", "category": "measure word"},
    {"simplified": "首", "traditional": "首", "pinyin": "shǒu", "english": "measure word for poems/songs", "category": "measure word"},
    {"simplified": "台", "traditional": "臺", "pinyin": "tái", "english": "measure word for machines/equipment", "category": "measure word"},
    {"simplified": "项", "traditional": "項", "pinyin": "xiàng", "english": "measure word for items/clauses", "category": "measure word"},
    {"simplified": "则", "traditional": "則", "pinyin": "zé", "english": "measure word for news items/rules", "category": "measure word"},

    # ============================================================
    # PARTICLES & FUNCTION WORDS (~10 words)
    # ============================================================
    {"simplified": "以来", "traditional": "以來", "pinyin": "yǐ lái", "english": "since; ever since", "category": "particle"},
    {"simplified": "以为", "traditional": "以為", "pinyin": "yǐ wéi", "english": "to think (mistakenly); to assume", "category": "particle"},
    {"simplified": "之", "traditional": "之", "pinyin": "zhī", "english": "of; 's (literary possessive)", "category": "particle"},
    {"simplified": "之间", "traditional": "之間", "pinyin": "zhī jiān", "english": "between; among", "category": "particle"},
    {"simplified": "之所以", "traditional": "之所以", "pinyin": "zhī suǒ yǐ", "english": "the reason why", "category": "particle"},
    {"simplified": "所", "traditional": "所", "pinyin": "suǒ", "english": "that which; what (function word)", "category": "particle"},

    # ============================================================
    # PRONOUNS & DETERMINERS (~8 words)
    # ============================================================
    {"simplified": "本", "traditional": "本", "pinyin": "běn", "english": "this; one's own; origin", "category": "pronoun"},
    {"simplified": "彼此", "traditional": "彼此", "pinyin": "bǐ cǐ", "english": "each other; one another; mutually", "category": "pronoun"},
    {"simplified": "某", "traditional": "某", "pinyin": "mǒu", "english": "certain; some; a particular", "category": "pronoun"},
    {"simplified": "任何", "traditional": "任何", "pinyin": "rèn hé", "english": "any; whatever; whichever", "category": "pronoun"},
    {"simplified": "一切", "traditional": "一切", "pinyin": "yí qiè", "english": "everything; all; every", "category": "pronoun"},
    {"simplified": "整个", "traditional": "整個", "pinyin": "zhěng gè", "english": "whole; entire; total", "category": "pronoun"},
    {"simplified": "各", "traditional": "各", "pinyin": "gè", "english": "each; every; various", "category": "pronoun"},

    # ============================================================
    # IDIOMS & SET PHRASES (~15 words)
    # ============================================================
    {"simplified": "比如", "traditional": "比如", "pinyin": "bǐ rú", "english": "for example; for instance; such as", "category": "phrase"},
    {"simplified": "比如说", "traditional": "比如說", "pinyin": "bǐ rú shuō", "english": "for example; for instance", "category": "phrase"},
    {"simplified": "不得了", "traditional": "不得了", "pinyin": "bù dé liǎo", "english": "extremely; terribly; exceedingly", "category": "phrase"},
    {"simplified": "差不多", "traditional": "差不多", "pinyin": "chà bu duō", "english": "almost; nearly; about the same", "category": "phrase"},
    {"simplified": "打交道", "traditional": "打交道", "pinyin": "dǎ jiāo dào", "english": "to have dealings with; to deal with", "category": "phrase"},
    {"simplified": "多亏", "traditional": "多虧", "pinyin": "duō kuī", "english": "thanks to; luckily", "category": "phrase"},
    {"simplified": "反而", "traditional": "反而", "pinyin": "fǎn ér", "english": "on the contrary; instead", "category": "phrase"},
    {"simplified": "换句话说", "traditional": "換句話說", "pinyin": "huàn jù huà shuō", "english": "in other words", "category": "phrase"},
    {"simplified": "来自", "traditional": "來自", "pinyin": "lái zì", "english": "to come from; to originate from", "category": "phrase"},
    {"simplified": "看来", "traditional": "看來", "pinyin": "kàn lái", "english": "it seems; it looks as if", "category": "phrase"},
    {"simplified": "免得", "traditional": "免得", "pinyin": "miǎn de", "english": "so as not to; in order to avoid", "category": "phrase"},
    {"simplified": "所谓", "traditional": "所謂", "pinyin": "suǒ wèi", "english": "so-called; what is called", "category": "phrase"},
    {"simplified": "总而言之", "traditional": "總而言之", "pinyin": "zǒng ér yán zhī", "english": "in short; to sum up; all in all", "category": "phrase"},

    # ============================================================
    # ADDITIONAL NOUNS (supplementary to reach 600+)
    # ============================================================
    {"simplified": "道德", "traditional": "道德", "pinyin": "dào dé", "english": "morality; ethics; virtue", "category": "noun"},
    {"simplified": "动力", "traditional": "動力", "pinyin": "dòng lì", "english": "motivation; driving force; power", "category": "noun"},
    {"simplified": "风险", "traditional": "風險", "pinyin": "fēng xiǎn", "english": "risk; hazard", "category": "noun"},
    {"simplified": "工程", "traditional": "工程", "pinyin": "gōng chéng", "english": "engineering; project", "category": "noun"},
    {"simplified": "功能", "traditional": "功能", "pinyin": "gōng néng", "english": "function; feature", "category": "noun"},
    {"simplified": "观念", "traditional": "觀念", "pinyin": "guān niàn", "english": "concept; idea; notion", "category": "noun"},
    {"simplified": "观点", "traditional": "觀點", "pinyin": "guān diǎn", "english": "viewpoint; standpoint; opinion", "category": "noun"},
    {"simplified": "后果", "traditional": "後果", "pinyin": "hòu guǒ", "english": "consequence; aftermath; result", "category": "noun"},
    {"simplified": "利益", "traditional": "利益", "pinyin": "lì yì", "english": "benefit; interest; profit", "category": "noun"},
    {"simplified": "秘密", "traditional": "秘密", "pinyin": "mì mì", "english": "secret; confidential", "category": "noun"},
    {"simplified": "命运", "traditional": "命運", "pinyin": "mìng yùn", "english": "fate; destiny", "category": "noun"},
    {"simplified": "矛盾", "traditional": "矛盾", "pinyin": "máo dùn", "english": "contradiction; conflict", "category": "noun"},
    {"simplified": "前途", "traditional": "前途", "pinyin": "qián tú", "english": "future; prospect; outlook", "category": "noun"},
    {"simplified": "趋势", "traditional": "趨勢", "pinyin": "qū shì", "english": "trend; tendency", "category": "noun"},
    {"simplified": "人口", "traditional": "人口", "pinyin": "rén kǒu", "english": "population", "category": "noun"},
    {"simplified": "人生", "traditional": "人生", "pinyin": "rén shēng", "english": "life (of a person); human life", "category": "noun"},
    {"simplified": "时代", "traditional": "時代", "pinyin": "shí dài", "english": "era; age; epoch", "category": "noun"},
    {"simplified": "时期", "traditional": "時期", "pinyin": "shí qī", "english": "period; phase; stage", "category": "noun"},
    {"simplified": "事业", "traditional": "事業", "pinyin": "shì yè", "english": "career; undertaking; enterprise", "category": "noun"},
    {"simplified": "手段", "traditional": "手段", "pinyin": "shǒu duàn", "english": "means; method; measure", "category": "noun"},
    {"simplified": "思想", "traditional": "思想", "pinyin": "sī xiǎng", "english": "thought; thinking; ideology", "category": "noun"},
    {"simplified": "挑战", "traditional": "挑戰", "pinyin": "tiǎo zhàn", "english": "challenge; to challenge", "category": "noun"},
    {"simplified": "通讯", "traditional": "通訊", "pinyin": "tōng xùn", "english": "communication; correspondence", "category": "noun"},
    {"simplified": "危害", "traditional": "危害", "pinyin": "wēi hài", "english": "harm; danger; to endanger", "category": "noun"},
    {"simplified": "物质", "traditional": "物質", "pinyin": "wù zhì", "english": "matter; material; substance", "category": "noun"},
    {"simplified": "现实", "traditional": "現實", "pinyin": "xiàn shí", "english": "reality; actual; realistic", "category": "noun"},
    {"simplified": "想法", "traditional": "想法", "pinyin": "xiǎng fa", "english": "idea; thought; opinion", "category": "noun"},
    {"simplified": "信任", "traditional": "信任", "pinyin": "xìn rèn", "english": "trust; confidence; to trust", "category": "noun"},
    {"simplified": "信心", "traditional": "信心", "pinyin": "xìn xīn", "english": "confidence; faith", "category": "noun"},
    {"simplified": "性格", "traditional": "性格", "pinyin": "xìng gé", "english": "character; personality; temperament", "category": "noun"},
    {"simplified": "性质", "traditional": "性質", "pinyin": "xìng zhì", "english": "nature; character; property", "category": "noun"},
    {"simplified": "意义", "traditional": "意義", "pinyin": "yì yì", "english": "meaning; significance; sense", "category": "noun"},
    {"simplified": "意识", "traditional": "意識", "pinyin": "yì shí", "english": "consciousness; awareness", "category": "noun"},
    {"simplified": "原则", "traditional": "原則", "pinyin": "yuán zé", "english": "principle; tenet", "category": "noun"},
    {"simplified": "智慧", "traditional": "智慧", "pinyin": "zhì huì", "english": "wisdom; intelligence", "category": "noun"},
    {"simplified": "资格", "traditional": "資格", "pinyin": "zī gé", "english": "qualification; credentials", "category": "noun"},
    {"simplified": "自然", "traditional": "自然", "pinyin": "zì rán", "english": "nature; natural; naturally", "category": "noun"},
    {"simplified": "组成", "traditional": "組成", "pinyin": "zǔ chéng", "english": "composition; to make up; to comprise", "category": "noun"},

    # --- More supplementary words ---
    {"simplified": "财富", "traditional": "財富", "pinyin": "cái fù", "english": "wealth; riches; fortune", "category": "noun"},
    {"simplified": "成本", "traditional": "成本", "pinyin": "chéng běn", "english": "cost (of production)", "category": "noun"},
    {"simplified": "成分", "traditional": "成分", "pinyin": "chéng fèn", "english": "component; ingredient; element", "category": "noun"},
    {"simplified": "成果", "traditional": "成果", "pinyin": "chéng guǒ", "english": "achievement; result; fruit", "category": "noun"},
    {"simplified": "成就", "traditional": "成就", "pinyin": "chéng jiù", "english": "achievement; accomplishment", "category": "noun"},
    {"simplified": "差距", "traditional": "差距", "pinyin": "chā jù", "english": "gap; disparity; difference", "category": "noun"},
    {"simplified": "价值", "traditional": "價值", "pinyin": "jià zhí", "english": "value; worth", "category": "noun"},
    {"simplified": "角度", "traditional": "角度", "pinyin": "jiǎo dù", "english": "angle; perspective; point of view", "category": "noun"},
    {"simplified": "阶段", "traditional": "階段", "pinyin": "jiē duàn", "english": "stage; phase; period", "category": "noun"},
    {"simplified": "精神", "traditional": "精神", "pinyin": "jīng shén", "english": "spirit; mind; vitality", "category": "noun"},
    {"simplified": "局面", "traditional": "局面", "pinyin": "jú miàn", "english": "situation; state of affairs", "category": "noun"},
    {"simplified": "空间", "traditional": "空間", "pinyin": "kōng jiān", "english": "space; room", "category": "noun"},
    {"simplified": "领域", "traditional": "領域", "pinyin": "lǐng yù", "english": "field; domain; realm; territory", "category": "noun"},
    {"simplified": "民族", "traditional": "民族", "pinyin": "mín zú", "english": "nationality; ethnic group; nation", "category": "noun"},
    {"simplified": "气氛", "traditional": "氣氛", "pinyin": "qì fēn", "english": "atmosphere; mood; ambiance", "category": "noun"},
    {"simplified": "社会", "traditional": "社會", "pinyin": "shè huì", "english": "society; social", "category": "noun"},
    {"simplified": "对策", "traditional": "對策", "pinyin": "duì cè", "english": "countermeasure; strategy", "category": "noun"},
    {"simplified": "方案", "traditional": "方案", "pinyin": "fāng àn", "english": "plan; scheme; proposal", "category": "noun"},
    {"simplified": "因素", "traditional": "因素", "pinyin": "yīn sù", "english": "factor; element", "category": "noun"},
]


def seed_hsk4():
    db = SessionLocal()
    try:
        existing = db.query(HanziWord).filter(HanziWord.hsk_level == 4).all()
        existing_simplified = {w.simplified for w in existing}

        added = 0
        for w in hsk4_words:
            if w["simplified"] not in existing_simplified:
                word = HanziWord(
                    simplified=w["simplified"],
                    traditional=w["traditional"],
                    pinyin=w["pinyin"],
                    english=w["english"],
                    hsk_level=4,
                    category=w.get("category")
                )
                db.add(word)
                added += 1

        db.commit()
        print(f"HSK 4: Added {added} new words (already had {len(existing_simplified)})")
    except Exception as e:
        print(f"Error: {e}")
        db.rollback()
    finally:
        db.close()


if __name__ == "__main__":
    seed_hsk4()
