"""
Add missing HSK 4 characters to the database
"""
from app.database import SessionLocal
from app.models import HanziWord

def add_hsk4_characters():
    """Add HSK 4 characters that are missing from the database"""

    # HSK 4 characters data with pinyin and basic meanings
    hsk4_chars = [
        # Format: (simplified, traditional, pinyin, english, strokes)
        ("淡", "淡", "dàn", "light (color); bland; indifferent", 11),
        ("售", "售", "shòu", "to sell", 11),
        ("益", "益", "yì", "benefit; profit; advantage", 10),
        ("会", "會", "huì", "can; to meet; meeting", 6),
        ("植", "植", "zhí", "to plant; to grow", 12),
        ("局", "局", "jú", "bureau; office; situation", 7),
        ("迅", "迅", "xùn", "rapid; swift", 6),
        ("湿", "濕", "shī", "wet; damp; moist", 12),
        ("姨", "姨", "yí", "aunt (mother's sister)", 9),
        ("切", "切", "qiē", "to cut; slice", 4),
        ("败", "敗", "bài", "to defeat; to lose", 8),
        ("智", "智", "zhì", "wisdom; intelligence", 12),
        ("销", "銷", "xiāo", "to sell; to market", 12),
        ("甚", "甚", "shèn", "very; extremely", 9),
        ("引", "引", "yǐn", "to lead; to pull", 4),
        ("官", "官", "guān", "official; government", 8),
        ("之", "之", "zhī", "of; it (classical)", 3),
        ("的", "的", "de", "of; possessive particle", 8),
        ("裹", "裹", "guǒ", "to wrap; to bind", 14),
        ("序", "序", "xù", "sequence; order; preface", 7),
        ("测", "測", "cè", "to measure; to test", 9),
        ("替", "替", "tì", "to replace; substitute", 12),
        ("弯", "彎", "wān", "bent; curved", 9),
        ("量", "量", "liàng", "quantity; amount; to measure", 12),
        ("措", "措", "cuò", "to arrange; measures", 11),
        ("腐", "腐", "fǔ", "rotten; decayed; corrupt", 14),
        ("航", "航", "háng", "boat; ship; to navigate", 10),
        ("扫", "掃", "sǎo", "to sweep; to clean", 6),
        ("脱", "脫", "tuō", "to take off; to shed", 11),
        ("均", "均", "jūn", "equal; even; all", 7),
        ("咸", "咸", "xián", "salty; all", 9),
        ("纷", "紛", "fēn", "confused; in disorder", 7),
        ("逛", "逛", "guàng", "to stroll; to roam", 10),
        ("塑", "塑", "sù", "to model; plastic", 13),
        ("操", "操", "cāo", "to operate; to drill", 16),
        ("聚", "聚", "jù", "to gather; to assemble", 14),
        ("填", "填", "tián", "to fill in; to stuff", 13),
        ("默", "默", "mò", "silent; quiet; to write from memory", 16),
        ("余", "餘", "yú", "surplus; extra", 7),
        ("森", "森", "sēn", "forest; dense", 12),
        ("帽", "帽", "mào", "hat; cap", 12),
        ("承", "承", "chéng", "to bear; to undertake", 8),
        ("县", "縣", "xiàn", "county", 7),
        ("几", "幾", "jǐ", "how many; several", 2),
        ("质", "質", "zhì", "quality; substance", 8),
        ("泉", "泉", "quán", "spring (water); fountain", 9),
        ("童", "童", "tóng", "child; childish", 12),
        ("延", "延", "yán", "to prolong; to extend", 6),
        ("编", "編", "biān", "to weave; to compile", 12),
        ("透", "透", "tòu", "to penetrate; thorough", 10),
        ("培", "培", "péi", "to cultivate; to train", 11),
        ("浓", "濃", "nóng", "thick; dense; strong", 9),
        ("却", "卻", "què", "but; yet; to decline", 7),
        ("竟", "竟", "jìng", "unexpectedly; actually", 11),
        ("辩", "辯", "biàn", "to debate; to argue", 16),
        ("减", "減", "jiǎn", "to reduce; to subtract", 11),
        ("丈", "丈", "zhàng", "measure word for length; husband", 3),
        ("泪", "淚", "lèi", "tears", 8),
        ("圾", "圾", "jī", "garbage; rubbish", 6),
        ("置", "置", "zhì", "to place; to put", 13),
        ("锻", "鍛", "duàn", "to forge; to temper", 14),
        ("迫", "迫", "pò", "to force; to compel", 8),
        ("独", "獨", "dú", "alone; single", 9),
        ("维", "維", "wéi", "to maintain; dimension", 11),
        ("轮", "輪", "lún", "wheel; to take turns", 8),
        ("伴", "伴", "bàn", "companion; to accompany", 7),
        ("纯", "純", "chún", "pure; simple", 7),
        ("巴", "巴", "bā", "to expect; to cling to", 4),
        ("寸", "寸", "cùn", "inch; very small", 3),
        ("映", "映", "yìng", "to reflect; to shine", 9),
        ("授", "授", "shòu", "to teach; to instruct", 11),
        ("骨", "骨", "gǔ", "bone", 9),
        ("未", "未", "wèi", "not yet; did not", 5),
        ("奖", "獎", "jiǎng", "prize; award", 9),
        ("尚", "尚", "shàng", "still; yet; to esteem", 8),
        ("分", "分", "fēn", "to divide; minute; point", 4),
        ("矮", "矮", "ǎi", "short; low", 13),
        ("躺", "躺", "tǎng", "to lie down", 15),
        ("笨", "笨", "bèn", "stupid; clumsy", 11),
        ("阵", "陣", "zhèn", "period; spell; burst", 6),
        ("案", "案", "àn", "case; table; record", 10),
        ("率", "率", "lǜ", "rate; frequency", 11),
        ("刷", "刷", "shuā", "to brush; to swipe", 8),
        ("项", "項", "xiàng", "item; term; clause", 9),
        ("醒", "醒", "xǐng", "to wake up; to sober up", 16),
        ("累", "累", "lèi", "tired; to accumulate", 11),
        ("即", "即", "jí", "namely; immediately", 7),
        ("季", "季", "jì", "season; period", 8),
        ("叶", "葉", "yè", "leaf; page", 5),
        ("婆", "婆", "pó", "grandmother; old woman", 11),
        ("宽", "寬", "kuān", "wide; broad", 10),
        ("孙", "孫", "sūn", "grandson; descendant", 6),
        ("免", "免", "miǎn", "to avoid; to exempt", 7),
        ("劲", "勁", "jìn", "strength; energy", 7),
        ("激", "激", "jī", "to excite; to arouse", 16),
        ("系", "系", "xì", "system; to tie", 7),
        ("尾", "尾", "wěi", "tail; end", 7),
        ("隔", "隔", "gé", "to separate; to isolate", 12),
        ("汇", "匯", "huì", "to converge; to collect", 5),
        ("毫", "毫", "háo", "fine hair; milli-", 11),
        ("府", "府", "fǔ", "mansion; government office", 8),
        ("申", "申", "shēn", "to state; to express", 5),
        ("络", "絡", "luò", "net; to connect", 9),
        ("殊", "殊", "shū", "special; unique", 10),
        ("挥", "揮", "huī", "to wave; to wield", 9),
        ("袋", "袋", "dài", "bag; sack", 11),
        ("摸", "摸", "mō", "to touch; to feel", 13),
        ("冰", "冰", "bīng", "ice; to freeze", 6),
        ("俗", "俗", "sú", "custom; vulgar", 9),
        ("陆", "陸", "lù", "land; continent", 7),
        ("谓", "謂", "wèi", "to call; to say", 11),
        ("既", "既", "jì", "already; since", 9),
        ("盘", "盤", "pán", "plate; to coil", 11),
        ("瓜", "瓜", "guā", "melon; gourd", 5),
        ("粗", "粗", "cū", "coarse; rough", 11),
        ("郎", "郎", "láng", "young man; gentleman", 8),
        ("寄", "寄", "jì", "to send; to mail", 11),
        ("叔", "叔", "shū", "uncle (father's younger brother)", 8),
        ("得", "得", "dé", "to get; to obtain", 11),
        ("镜", "鏡", "jìng", "mirror; lens", 16),
        ("良", "良", "liáng", "good; fine", 7),
        ("中", "中", "zhōng", "middle; center", 4),
        ("逐", "逐", "zhú", "to chase; gradually", 10),
        ("肚", "肚", "dù", "belly; stomach", 7),
        ("财", "財", "cái", "wealth; money", 7),
        ("抄", "抄", "chāo", "to copy; to plagiarize", 7),
        ("促", "促", "cù", "to urge; to promote", 9),
        ("斗", "鬥", "dòu", "to fight; to struggle", 4),
        ("针", "針", "zhēn", "needle; to inject", 7),
        ("辣", "辣", "là", "spicy; hot", 14),
        ("刺", "刺", "cì", "thorn; to stab", 8),
        ("晒", "曬", "shài", "to dry in the sun", 10),
        ("厚", "厚", "hòu", "thick; deep", 9),
        ("窗", "窗", "chuāng", "window", 12),
        ("治", "治", "zhì", "to govern; to cure", 8),
        ("勇", "勇", "yǒng", "brave; courageous", 9),
        ("型", "型", "xíng", "model; type", 9),
        ("江", "江", "jiāng", "river", 6),
        ("战", "戰", "zhàn", "war; to fight", 9),
        ("虑", "慮", "lǜ", "to consider; anxiety", 10),
        ("牙", "牙", "yá", "tooth; ivory", 4),
        ("巾", "巾", "jīn", "towel; napkin", 3),
        ("虫", "蟲", "chóng", "insect; worm", 6),
        ("则", "則", "zé", "rule; then", 6),
        ("遇", "遇", "yù", "to meet; to encounter", 12),
        ("址", "址", "zhǐ", "site; location", 7),
        ("源", "源", "yuán", "source; origin", 13),
        ("扬", "揚", "yáng", "to raise; to spread", 6),
        ("阅", "閱", "yuè", "to read; to review", 10),
        ("户", "戶", "hù", "household; door", 4),
        ("临", "臨", "lín", "to face; to approach", 9),
        ("梦", "夢", "mèng", "dream", 11),
        ("赏", "賞", "shǎng", "to reward; to appreciate", 12),
        ("弱", "弱", "ruò", "weak; feeble", 10),
        ("择", "擇", "zé", "to select; to choose", 8),
        ("阿", "阿", "ā", "prefix for names; to flatter", 7),
        ("获", "獲", "huò", "to obtain; to capture", 10),
        ("与", "與", "yǔ", "and; with; to give", 3),
        ("疗", "療", "liáo", "to treat; therapy", 7),
        ("豆", "豆", "dòu", "bean; pea", 7),
        ("雷", "雷", "léi", "thunder; mine", 13),
        ("担", "擔", "dān", "to carry; to bear", 8),
        ("购", "購", "gòu", "to buy; to purchase", 8),
        ("缓", "緩", "huǎn", "slow; gradual", 12),
        ("闹", "鬧", "nào", "noisy; to make noise", 8),
        ("妻", "妻", "qī", "wife", 8),
        ("移", "移", "yí", "to move; to shift", 11),
        ("巨", "巨", "jù", "huge; gigantic", 4),
        ("戴", "戴", "dài", "to wear; to put on", 17),
        ("描", "描", "miáo", "to depict; to describe", 11),
        ("兵", "兵", "bīng", "soldier; weapon", 7),
        ("抱", "抱", "bào", "to hold; to embrace", 8),
        ("挑", "挑", "tiāo", "to carry; to choose", 9),
        ("擦", "擦", "cā", "to wipe; to rub", 17),
        ("缩", "縮", "suō", "to shrink; to reduce", 14),
        ("席", "席", "xí", "seat; banquet", 10),
        ("秘", "秘", "mì", "secret; mysterious", 10),
        ("无", "無", "wú", "without; none", 4),
        ("固", "固", "gù", "solid; firm", 8),
        ("袜", "襪", "wà", "sock; stocking", 10),
        ("粮", "糧", "liáng", "grain; food", 13),
        ("贴", "貼", "tiē", "to stick; to paste", 9),
        ("附", "附", "fù", "to attach; to enclose", 7),
        ("趋", "趨", "qū", "to tend toward; to hasten", 12),
        ("耳", "耳", "ěr", "ear", 6),
        ("微", "微", "wēi", "tiny; micro", 13),
        ("翻", "翻", "fān", "to turn over; to translate", 18),
        ("酸", "酸", "suān", "sour; acid", 14),
        ("伞", "傘", "sǎn", "umbrella", 6),
        ("胸", "胸", "xiōng", "chest; breast", 10),
        ("抽", "抽", "chōu", "to draw out; to smoke", 8),
        ("种", "種", "zhǒng", "kind; type; to plant", 9),
        ("寒", "寒", "hán", "cold; poor", 12),
        ("征", "征", "zhēng", "to levy; to recruit", 8),
        ("守", "守", "shǒu", "to guard; to defend", 6),
        ("厘", "厘", "lí", "millimeter; tiny", 9),
        ("顶", "頂", "dǐng", "top; peak; to carry on the head", 8),
        ("稳", "穩", "wěn", "stable; steady", 14),
        ("统", "統", "tǒng", "to unite; system", 9),
        ("居", "居", "jū", "to reside; to dwell", 8),
        ("限", "限", "xiàn", "limit; to restrict", 8),
        ("啊", "啊", "ā", "ah; particle expressing surprise", 10),
        ("哪", "哪", "nǎ", "which; where", 9),
        ("呀", "呀", "yā", "particle expressing surprise", 7),
        ("递", "遞", "dì", "to hand over; to pass", 10),
        ("构", "構", "gòu", "to construct; structure", 8),
        ("矿", "礦", "kuàng", "ore; mine", 8),
        ("列", "列", "liè", "row; to list", 6),
        ("召", "召", "zhào", "to summon; to convene", 5),
        ("政", "政", "zhèng", "politics; government", 9),
        ("乎", "乎", "hū", "in; at; from (classical)", 5),
        ("宝", "寶", "bǎo", "treasure; precious", 8),
        ("密", "密", "mì", "dense; secret", 11),
        ("秀", "秀", "xiù", "elegant; beautiful; to show", 7),
        ("吸", "吸", "xī", "to inhale; to absorb", 6),
        ("聊", "聊", "liáo", "to chat; to have a talk", 11),
        ("释", "釋", "shì", "to explain; to release", 12),
        ("兴", "興", "xīng", "flourishing; to rise", 6),
        ("权", "權", "quán", "power; right", 6),
        ("码", "碼", "mǎ", "code; number", 8),
        ("料", "料", "liào", "material; to anticipate", 10),
        ("归", "歸", "guī", "to return; to belong to", 5),
        ("研", "研", "yán", "to grind; to research", 9),
        ("译", "譯", "yì", "to translate; to interpret", 7),
        ("距", "距", "jù", "distance; to be apart", 11),
        ("闭", "閉", "bì", "to close; to shut", 6),
        ("似", "似", "sì", "to resemble; similar", 6),
        ("士", "士", "shì", "scholar; soldier", 3),
        ("综", "綜", "zōng", "comprehensive; to sum up", 11),
        ("奋", "奮", "fèn", "to exert; to strive", 8),
        ("暗", "暗", "àn", "dark; dim; secret", 13),
        ("堵", "堵", "dǔ", "to block; to stop up", 11),
        ("尽", "盡", "jìn", "to exhaust; to use up", 6),
        ("著", "著", "zhù", "to write; to attach; book", 11),
        ("避", "避", "bì", "to avoid; to shun", 16),
        ("盖", "蓋", "gài", "lid; cover; to build", 11),
        ("细", "細", "xì", "thin; fine; detailed", 8),
        ("俩", "倆", "liǎ", "two; both", 9),
        ("摆", "擺", "bǎi", "to arrange; to display", 13),
        ("施", "施", "shī", "to carry out; to bestow", 9),
        ("致", "致", "zhì", "to send; to cause", 10),
        ("寻", "尋", "xún", "to seek; to search", 6),
        ("诚", "誠", "chéng", "sincere; honest", 8),
        ("货", "貨", "huò", "goods; commodity", 8),
        ("毕", "畢", "bì", "to finish; to complete", 6),
        ("依", "依", "yī", "to rely on; according to", 8),
        ("肥", "肥", "féi", "fat; fertile", 8),
        ("贝", "貝", "bèi", "shell; precious", 4),
        ("敌", "敵", "dí", "enemy; to oppose", 10),
        ("梯", "梯", "tī", "ladder; stairs", 11),
        ("怀", "懷", "huái", "bosom; to cherish", 7),
        ("幼", "幼", "yòu", "young; immature", 5),
        ("阶", "階", "jiē", "step; rank", 6),
        ("浅", "淺", "qiǎn", "shallow; simple", 8),
        ("企", "企", "qǐ", "to plan; enterprise", 6),
        ("究", "究", "jiū", "to investigate; to study", 7),
        ("疑", "疑", "yí", "to doubt; to suspect", 14),
        ("尺", "尺", "chǐ", "ruler; foot (measure)", 4),
        ("炼", "煉", "liàn", "to refine; to smelt", 9),
        ("烧", "燒", "shāo", "to burn; to cook", 10),
        ("角", "角", "jiǎo", "angle; corner; horn", 7),
        ("闪", "閃", "shǎn", "to flash; to dodge", 5),
        ("松", "松", "sōng", "pine tree; loose", 8),
        ("潮", "潮", "cháo", "tide; damp; fashionable", 15),
        ("扩", "擴", "kuò", "to expand; to enlarge", 6),
        ("倍", "倍", "bèi", "times; -fold", 10),
        ("史", "史", "shǐ", "history; chronicles", 5),
        ("卷", "卷", "juàn", "volume; scroll; to roll", 8),
        ("括", "括", "kuò", "to include; to embrace", 9),
        ("妇", "婦", "fù", "woman; married woman", 6),
        ("律", "律", "lǜ", "law; rule; discipline", 9),
        ("登", "登", "dēng", "to climb; to mount", 12),
        ("打", "打", "dǎ", "to hit; to strike", 5),
        ("渐", "漸", "jiàn", "gradually", 11),
        ("述", "述", "shù", "to state; to narrate", 8),
        ("玉", "玉", "yù", "jade; precious stone", 5),
        ("阻", "阻", "zǔ", "to block; to hinder", 7),
        ("符", "符", "fú", "mark; symbol; to conform", 11),
        ("严", "嚴", "yán", "strict; severe", 7),
        ("帅", "帥", "shuài", "handsome; commander", 5),
        ("诗", "詩", "shī", "poetry; poem", 8),
        ("迟", "遲", "chí", "late; slow; to delay", 7),
        ("暑", "暑", "shǔ", "heat; hot weather", 12),
        ("亚", "亞", "yà", "Asia; second", 6),
        ("含", "含", "hán", "to contain; to hold", 7),
        ("燃", "燃", "rán", "to burn; to ignite", 16),
        ("穷", "窮", "qióng", "poor; exhausted", 7),
        ("赞", "贊", "zàn", "to praise; to support", 16),
        ("盐", "鹽", "yán", "salt", 10),
        ("彻", "徹", "chè", "thorough; penetrating", 7),
        ("趣", "趣", "qù", "interest; interesting", 15),
        ("鲜", "鮮", "xiān", "fresh; bright", 14),
        ("棵", "棵", "kē", "measure word for trees", 12),
        ("林", "林", "lín", "forest; woods", 8),
        ("兄", "兄", "xiōng", "elder brother", 5),
        ("招", "招", "zhāo", "to recruit; to attract", 8),
        ("途", "途", "tú", "way; route", 10),
        ("沉", "沉", "chén", "to sink; heavy", 7),
        ("投", "投", "tóu", "to throw; to invest", 7),
        ("惊", "驚", "jīng", "to startle; to surprise", 11),
        ("圆", "圓", "yuán", "circle; round", 10),
        ("腰", "腰", "yāo", "waist; middle", 13),
        ("摇", "搖", "yáo", "to shake; to wave", 13),
        ("呼", "呼", "hū", "to shout; to exhale", 8),
        ("垃", "垃", "lā", "garbage; trash", 8),
        ("吧", "吧", "bā", "particle indicating suggestion", 7),
    ]

    db = SessionLocal()
    try:
        added_count = 0
        updated_count = 0

        for simp, trad, py, eng, strokes in hsk4_chars:
            # Check if character already exists
            existing = db.query(HanziWord).filter(
                HanziWord.simplified == simp,
                HanziWord.hsk_level == 4
            ).first()

            if existing:
                # Update if needed
                if not existing.english or existing.english == "":
                    existing.english = eng
                    existing.traditional = trad
                    existing.pinyin = py
                    updated_count += 1
            else:
                # Add new character
                new_word = HanziWord(
                    simplified=simp,
                    traditional=trad,
                    pinyin=py,
                    english=eng,
                    hsk_level=4
                )
                db.add(new_word)
                added_count += 1

        db.commit()
        print(f"\nSuccess!")
        print(f"   Added: {added_count} new characters")
        print(f"   Updated: {updated_count} existing characters")
        print(f"   Total HSK 4 characters: {len(hsk4_chars)}")

    except Exception as e:
        print(f"Error: {e}")
        db.rollback()
    finally:
        db.close()

if __name__ == "__main__":
    print("Adding HSK 4 characters to database...")
    add_hsk4_characters()
