"""add_attachment_and_selector_to_feedback

Revision ID: 18c0af1c1c70
Revises: f1a2b3c4d5e6
Create Date: 2026-06-18 10:44:50.839743

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '18c0af1c1c70'
down_revision = 'f1a2b3c4d5e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('attachment_url', sa.Text(), nullable=True))
    op.add_column('feedback', sa.Column('element_selector', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback', 'element_selector')
    op.drop_column('feedback', 'attachment_url')
    # ### end Alembic commands ###
