"""add_typing_progress_table

Revision ID: 1ecbd08a832b
Revises: 11bd916caad6
Create Date: 2025-12-26 19:29:20.486241

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1ecbd08a832b'
down_revision = '11bd916caad6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('story_bookmarks')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('story_bookmarks',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('story_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], name='story_bookmarks_story_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='story_bookmarks_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'story_id', name='story_bookmarks_pkey')
    )
    # ### end Alembic commands ###
