"""initial migration

Revision ID: 28f27190032a
Revises: 
Create Date: 2025-12-03 14:46:37.879416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28f27190032a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hanzi_words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simplified', sa.String(), nullable=False),
    sa.Column('traditional', sa.String(), nullable=False),
    sa.Column('pinyin', sa.String(), nullable=False),
    sa.Column('english', sa.Text(), nullable=False),
    sa.Column('hsk_level', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hanzi_words_hsk_level'), 'hanzi_words', ['hsk_level'], unique=False)
    op.create_index(op.f('ix_hanzi_words_id'), 'hanzi_words', ['id'], unique=False)
    op.create_index(op.f('ix_hanzi_words_simplified'), 'hanzi_words', ['simplified'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('stories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('hsk_level', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stories_hsk_level'), 'stories', ['hsk_level'], unique=False)
    op.create_index(op.f('ix_stories_id'), 'stories', ['id'], unique=False)
    op.create_table('user_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('familiarity_level', sa.Integer(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('last_reviewed', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['hanzi_words.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_progress_id'), 'user_progress', ['id'], unique=False)
    op.create_table('vocabulary_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vocabulary_sets_id'), 'vocabulary_sets', ['id'], unique=False)
    op.create_table('story_words',
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['hanzi_words.id'], ),
    sa.PrimaryKeyConstraint('story_id', 'word_id')
    )
    op.create_table('vocabulary_set_words',
    sa.Column('vocabulary_set_id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vocabulary_set_id'], ['vocabulary_sets.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['hanzi_words.id'], ),
    sa.PrimaryKeyConstraint('vocabulary_set_id', 'word_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vocabulary_set_words')
    op.drop_table('story_words')
    op.drop_index(op.f('ix_vocabulary_sets_id'), table_name='vocabulary_sets')
    op.drop_table('vocabulary_sets')
    op.drop_index(op.f('ix_user_progress_id'), table_name='user_progress')
    op.drop_table('user_progress')
    op.drop_index(op.f('ix_stories_id'), table_name='stories')
    op.drop_index(op.f('ix_stories_hsk_level'), table_name='stories')
    op.drop_table('stories')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_hanzi_words_simplified'), table_name='hanzi_words')
    op.drop_index(op.f('ix_hanzi_words_id'), table_name='hanzi_words')
    op.drop_index(op.f('ix_hanzi_words_hsk_level'), table_name='hanzi_words')
    op.drop_table('hanzi_words')
    # ### end Alembic commands ###
