"""feedback_multiple_attachments_selectors

Revision ID: 4f4e29a86896
Revises: 18c0af1c1c70
Create Date: 2026-06-18 14:57:52.756827

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '4f4e29a86896'
down_revision = '18c0af1c1c70'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('attachment_urls', sa.JSON(), nullable=True))
    op.add_column('feedback', sa.Column('element_selectors', sa.JSON(), nullable=True))
    op.drop_column('feedback', 'element_selector')
    op.drop_column('feedback', 'attachment_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('attachment_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('feedback', sa.Column('element_selector', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('feedback', 'element_selectors')
    op.drop_column('feedback', 'attachment_urls')
    # ### end Alembic commands ###
    # NOTE: autogenerate also emitted a `create_table('story_bookmarks')` here because
    # that table is managed via raw SQL (see routers/stories.py) and has no ORM model.
    # It was removed — upgrade() never drops the table, so downgrade() must not recreate it.
