"""feedback_multiple_attachments_selectors

Revision ID: 4f4e29a86896
Revises: 18c0af1c1c70
Create Date: 2026-06-18 14:57:52.756827

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4f4e29a86896'
down_revision = '18c0af1c1c70'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('attachment_urls', sa.JSON(), nullable=True))
    op.add_column('feedback', sa.Column('element_selectors', sa.JSON(), nullable=True))
    op.drop_column('feedback', 'element_selector')
    op.drop_column('feedback', 'attachment_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('attachment_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('feedback', sa.Column('element_selector', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('feedback', 'element_selectors')
    op.drop_column('feedback', 'attachment_urls')
    # ### end Alembic commands ###
    op.create_table('story_bookmarks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('story_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], name='story_bookmarks_story_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='story_bookmarks_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='story_bookmarks_pkey'),
    sa.UniqueConstraint('user_id', 'story_id', name='story_bookmarks_user_id_story_id_key')
    )
    # ### end Alembic commands ###
