"""make position nullable

Revision ID: 904e8634d3d4
Revises: 28f27190032a
Create Date: 2025-12-03 14:48:06.612081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '904e8634d3d4'
down_revision = '28f27190032a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('story_words', 'position',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('story_words', 'position',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
