"""Add title_english to Story model

Revision ID: b94152a356ac
Revises: 6421228aa32f
Create Date: 2025-12-07 11:05:44.989114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b94152a356ac'
down_revision = '6421228aa32f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('title_english', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stories', 'title_english')
    # ### end Alembic commands ###
